Level - 11 :  Missing Values, Duplicates & Data Quality

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('all_neet_marks_2607.csv')

In [3]:
# 201. Count missing values in every column.

df.isnull().sum()

state          0
city           0
center_name    0
center_num     0
Srlno.         0
Marks          0
dtype: int64

In [4]:
# 202. Display rows containing at least one missing value.

# isnull() → har cell ko check karta hai ki missing hai ya nahi
# sum(axis=1) → har row mein total missing values count karta hai
df_202 = df.isnull().sum(axis=1)

# Jis row mein missing values ka count 0 se greater hai,
# us row mein kam se kam 1 missing value hai
df_202 = df.loc[0]

print(df_202)

state          ANDAMAN AND NICOBAR ISLANDS (UT)
city                                 PORT BLAIR
center_name            KENDRIYA VIDYALAYA NO. 1
center_num                               110101
Srlno.                                        1
Marks                                        46
Name: 0, dtype: object

In [5]:
# 203. Display rows where Marks is missing.

df.loc[df['Marks'].isnull()]

Empty DataFrame
Columns: [state, city, center_name, center_num, Srlno., Marks]
Index: []

In [6]:
# 204. Display rows where state is missing.


df.loc[df['state'].isnull()]

Empty DataFrame
Columns: [state, city, center_name, center_num, Srlno., Marks]
Index: []

In [7]:
# 205. Display rows where city is missing.

df.loc[df['city'].isnull()]

Empty DataFrame
Columns: [state, city, center_name, center_num, Srlno., Marks]
Index: []

In [8]:
# 206. Fill missing Marks with the median Marks.

df_206 = df['Marks'].fillna(df['Marks'].median())

print(df_206)

0           46
1          226
2          449
3          424
4          222
          ...
2333157    279
2333158    102
2333159     14
2333160    179
2333161     91
Name: Marks, Length: 2333162, dtype: int64

In [9]:
# 207. Fill missing Marks with the mean Marks.

df_207 = df['Marks'].fillna(df['Marks'].mean())
print(df_207)

0           46
1          226
2          449
3          424
4          222
          ...
2333157    279
2333158    102
2333159     14
2333160    179
2333161     91
Name: Marks, Length: 2333162, dtype: int64

In [10]:
# 208. Fill missing categorical values with 'Unknown'.

df_208 = df['city'].fillna('unknown')
print(df_208)

0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str

In [16]:
# 209. Drop rows where Marks is missing.

df_209 = df.drop(df[df['Marks'].isnull()].index)

print(df_209)

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[2333162 rows x 6 columns]

In [26]:
# 210. Drop rows where state or city is missing.

df_210_mssing = df.loc[df['state'].isnull() | df['city'].isnull()].index
df_210 = df.drop(df_210_mssing)
print(df_210)

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[2333162 rows x 6 columns]

In [31]:
# 211. Check for duplicated Srlno values.

df_211 = df['Srlno.'].duplicated().sum()

print(df_211)

2331194

In [ ]:
# 212. Display all duplicated Srlno records.

# duplicated() duplicate Srlno values ko identify karta hai.
df_212 = df.loc[df['Srlno.'].duplicated()]

print(df_212)

                                    state        city  \
461      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
462      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
463      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
464      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
465      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                                     center_name  center_num  Srlno.  Marks
461      DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102       1    115
462      DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102       2     30
463      DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102       3    347
464      DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102       4    543
465      DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102       5    220
...                                          ...         ...     ...    ...
2333157                    CHAKDAHA MODEL SCHOOL      461312     135    279
2333158                    CHAKDAHA MODEL SCHOOL      461312     136    102
2333159                    CHAKDAHA MODEL SCHOOL      461312     137     14
2333160                    CHAKDAHA MODEL SCHOOL      461312     138    179
2333161                    CHAKDAHA MODEL SCHOOL      461312     139     91

[2331194 rows x 6 columns]

In [ ]:
# 213. Remove duplicate rows while keeping the first occurrence.

In [ ]:
# 214. Remove duplicate rows while keeping the last occurrence.

In [ ]:
# 215. Check whether center_num is unique within center_name.

In [ ]:
# 216. Check whether every row has a valid Marks value between 0 and 720.

In [ ]:
# 217. Display rows with Marks outside the valid 0–720 range.

In [ ]:
# 218. Count invalid Marks values outside the range 0–720.

In [ ]:
# 219. Check for blank strings in state, city, and center_name.

In [ ]:
# 220. Replace blank strings with missing values.