Level - 11 :  Missing Values, Duplicates & Data Quality

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv('all_neet_marks_2607.csv')

In [49]:
# 201. Count missing values in every column.

df.isnull().sum()

state          0
city           0
center_name    0
center_num     0
Srlno.         0
Marks          0
dtype: int64

In [50]:
# 202. Display rows containing at least one missing value.

# isnull() → har cell ko check karta hai ki missing hai ya nahi
# sum(axis=1) → har row mein total missing values count karta hai
df_202 = df.isnull().sum(axis=1)

# Jis row mein missing values ka count 0 se greater hai,
# us row mein kam se kam 1 missing value hai
df_202 = df.loc[0]

print(df_202)

state          ANDAMAN AND NICOBAR ISLANDS (UT)
city                                 PORT BLAIR
center_name            KENDRIYA VIDYALAYA NO. 1
center_num                               110101
Srlno.                                        1
Marks                                        46
Name: 0, dtype: object

In [51]:
# 203. Display rows where Marks is missing.

df.loc[df['Marks'].isnull()]

Empty DataFrame
Columns: [state, city, center_name, center_num, Srlno., Marks]
Index: []

In [52]:
# 204. Display rows where state is missing.


df.loc[df['state'].isnull()]

Empty DataFrame
Columns: [state, city, center_name, center_num, Srlno., Marks]
Index: []

In [53]:
# 205. Display rows where city is missing.

df.loc[df['city'].isnull()]

Empty DataFrame
Columns: [state, city, center_name, center_num, Srlno., Marks]
Index: []

In [54]:
# 206. Fill missing Marks with the median Marks.

df_206 = df['Marks'].fillna(df['Marks'].median())

print(df_206)

0           46
1          226
2          449
3          424
4          222
          ...
2333157    279
2333158    102
2333159     14
2333160    179
2333161     91
Name: Marks, Length: 2333162, dtype: int64

In [55]:
# 207. Fill missing Marks with the mean Marks.

df_207 = df['Marks'].fillna(df['Marks'].mean())
print(df_207)

0           46
1          226
2          449
3          424
4          222
          ...
2333157    279
2333158    102
2333159     14
2333160    179
2333161     91
Name: Marks, Length: 2333162, dtype: int64

In [56]:
# 208. Fill missing categorical values with 'Unknown'.

df_208 = df['city'].fillna('unknown')
print(df_208)

0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str

In [57]:
# 209. Drop rows where Marks is missing.

df_209 = df.drop(df[df['Marks'].isnull()].index)

print(df_209)

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[2333162 rows x 6 columns]

In [58]:
# 210. Drop rows where state or city is missing.

df_210_mssing = df.loc[df['state'].isnull() | df['city'].isnull()].index  # State ya city mein missing value wali rows ke index nikalna

df_210 = df.drop(df_210_mssing)  # Missing value wali rows ko DataFrame se remove karna

print(df_210)  # Missing rows remove hone ke baad final DataFrame print karna

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[2333162 rows x 6 columns]

In [59]:
# 211. Check for duplicated Srlno values.

df_211 = df['Srlno.'].duplicated().sum()

print(df_211)

2331194

In [60]:
# 212. Display all duplicated Srlno records.

# duplicated() duplicate Srlno values ko identify karta hai.
df_212 = df.loc[df['Srlno.'].duplicated()]

print(df_212)

                                    state        city  \
461      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
462      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
463      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
464      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
465      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                                     center_name  center_num  Srlno.  Marks
461      DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102       1    115
462      DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102       2     30
463      DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102       3    347
464      DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102       4    543
465      DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102       5    220
...                                          ...         ...     ...    ...
2333157                    CHAKDAHA MODEL SCHOOL      461312     135    279
2333158                    CHAKDAHA MODEL SCHOOL      461312     136    102
2333159                    CHAKDAHA MODEL SCHOOL      461312     137     14
2333160                    CHAKDAHA MODEL SCHOOL      461312     138    179
2333161                    CHAKDAHA MODEL SCHOOL      461312     139     91

[2331194 rows x 6 columns]

In [61]:
# 213. Remove duplicate rows while keeping the first occurrence.

df_213 = df.drop_duplicates(keep='first')  # Duplicate rows hata kar pehli row rakhna

print(df_213)

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[2333162 rows x 6 columns]

In [62]:
# 214. Remove duplicate rows while keeping the last occurrence.

df_214 = df.drop_duplicates(keep='last')  # Duplicate rows hata kar aakhri row rakhna

print(df_214)

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[2333162 rows x 6 columns]

In [63]:
# 215. Check whether center_num is unique within center_name.

df_215 = df.groupby('center_name').agg({'center_num': 'nunique'})  # Har center_name ke unique center_num count karna

print(df_215)

                                                    center_num
center_name
 GYANJYOTI K.R VIDYALAYA MAULIBHATA GADTOR NUAP...           1
(UNIT-2) SCHOOL OF ENGINEERING, R.K.UNIVERSITY               1
A G PUBLLIC SCHOOL                                           1
A M N M MODEL SCHOOL CHETGANJ VARANASI UP                    1
A N COLLEGE                                                  1
...                                                        ...
ZEN SCHOOL                                                   1
ZENITH CONVENT SCHOOL                                        1
ZENITH INTERNATIONAL SCHOOL                                  1
ZILLA PUBLIC SCHOOL                                          1
ZULAL BHILAJIRAO PATIL COLLEGE ( JAI HIND SENIO...           1

[4400 rows x 1 columns]

In [64]:
# 216. Check whether every row has a valid Marks value between 0 and 720.

df_216 = df.loc[(df['Marks'] >= 0) & (df['Marks'] <= 720)]  # 0 se 720 ke beech ke Marks wali rows select karna

print(df_216)

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[2323685 rows x 6 columns]

In [65]:
# 217. Display rows with Marks outside the valid 0–720 range.

df_217 = df.loc[(df['Marks'] < 0) | (df['Marks'] > 720)].reset_index()  # 0 se kam ya 720 se zyada Marks wali rows nikalna yani ek tarike se outside likha yani invalid 

print(df_217)

        index                             state        city  \
0         140  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1         141  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2         327  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        1594                    ANDHRA PRADESH      GUNTUR
4        1958                    ANDHRA PRADESH      GUNTUR
...       ...                               ...         ...
9472  2331049                       WEST BENGAL     KALYANI
9473  2331972                       WEST BENGAL     KALYANI
9474  2332224                       WEST BENGAL     KALYANI
9475  2332562                       WEST BENGAL     KALYANI
9476  2332969                       WEST BENGAL     KALYANI

                                          center_name  center_num  Srlno.  \
0                            KENDRIYA VIDYALAYA NO. 1      110101     141
1                            KENDRIYA VIDYALAYA NO. 1      110101     142
2                            KENDRIYA VIDYALAYA NO. 1      110101     328
3                 LITTLE FLOWER ENGLISH MEDIUM SCHOOL      120101     570
4                  CHALAPATHI INSTITUTE OF TECHNOLOGY      120102     233
...                                               ...         ...     ...
9472  GHOSHPARA SRASWATI TRUST ESTATE VIDYAPITH (H.S)      461306     130
9473                DELHI WORLD PUBLIC SCHOOL KALYANI      461308     213
9474                             KALYANI SHIKSHAYATAN      461309      53
9475                             KALYANI SHIKSHAYATAN      461309     391
9476                               GARDEN HIGH SCHOOL      461311     125

      Marks
0        -5
1        -2
2        -3
3        -3
4        -5
...     ...
9472     -3
9473     -2
9474     -5
9475     -6
9476    -10

[9477 rows x 7 columns]

In [66]:
# 218. Count invalid Marks values outside the range 0–720.

df_218 = df.loc[(df['Marks'] < 0) | (df['Marks'] > 720)].sum()   # Invalid Marks ki total count nikalna

print(df_218)

# Invalid Marks ka total = -9880 ye hi  mai nikal raha tha

state          ANDAMAN AND NICOBAR ISLANDS (UT)ANDAMAN AND NI...
city           PORT BLAIRPORT BLAIRPORT BLAIRGUNTURGUNTURGUNT...
center_name    KENDRIYA VIDYALAYA NO. 1KENDRIYA VIDYALAYA NO....
center_num                                            3090790182
Srlno.                                                   2643480
Marks                                                     -98880
dtype: object

In [71]:
# 219. Check for blank strings in state, city, and center_name.

df_219 = df.loc[(df['state']== " ") | (df['city'] == " ") | (df['center_name'] == " ")]        # In columns mein blank values wali rows nikalna hu mai 

print(df_219)

Empty DataFrame
Columns: [state, city, center_name, center_num, Srlno., Marks]
Index: []

In [ ]:
# 220. Replace blank strings with missing values.

df_220 = df.replace(' ',None)      # Blank strings ko missing value banana
   
print(df_220)  # Blank strings ko missing values se replace karne ke baad DataFrame print karna

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[2333162 rows x 6 columns]