In [277]:
import pandas as pd

300_Question_of_Pyth0n_Pandas_Data_Frame

Level - 1

In [278]:
# 1. Load the NEET dataset into a pandas DataFrame named df.

df = pd.read_csv('all_neet_marks_2607.csv')

In [279]:
# 2. Display the first 5 rows of the DataFrame.

df.head()

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222

In [280]:
# 3. Display the last 5 rows of the DataFrame.

df.tail()

,state,city,center_name,center_num,Srlno.,Marks
2333157,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,135,279
2333158,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,136,102
2333159,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,137,14
2333160,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,138,179
2333161,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,139,91

In [281]:
# 4. Display the first 10 rows of the DataFrame.

df.head(10)

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222
5,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,6,181
6,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,7,115
7,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,8,127
8,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,9,88
9,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,10,77

In [282]:
# 5. Display the last 10 rows of the DataFrame.

df.tail(10)

,state,city,center_name,center_num,Srlno.,Marks
2333152,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,130,90
2333153,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,131,250
2333154,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,132,130
2333155,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,133,55
2333156,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,134,130
2333157,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,135,279
2333158,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,136,102
2333159,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,137,14
2333160,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,138,179
2333161,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,139,91

In [283]:
# 6. Display the shape of the DataFrame.

df.shape

(2333162, 6)

In [284]:
# 7. Display the number of rows in the DataFrame.

df.shape[0]

2333162

In [285]:
#8. Display the number of columns in the DataFrame.
df.shape[1]

6

In [286]:
#9. Display all column names.
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [287]:
#10. Display the DataFrame index.

df.index

RangeIndex(start=0, stop=2333162, step=1)

In [288]:
# 11. Display the data types of all columns.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2333162 entries, 0 to 2333161
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   state        str
 1   city         str
 2   center_name  str
 3   center_num   int64
 4   Srlno.       int64
 5   Marks        int64
dtypes: int64(3), str(3)
memory usage: 106.8 MB

In [289]:
# 12. Generate a concise summary of the DataFrame using info().

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2333162 entries, 0 to 2333161
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   state        str
 1   city         str
 2   center_name  str
 3   center_num   int64
 4   Srlno.       int64
 5   Marks        int64
dtypes: int64(3), str(3)
memory usage: 106.8 MB

In [290]:
# 13. Generate descriptive statistics for the Marks column.
df['Marks'].describe()

count    2.333162e+06
mean     2.171566e+02
std      1.662400e+02
min     -1.800000e+02
25%      8.700000e+01
50%      1.630000e+02
75%      3.130000e+02
max      7.200000e+02
Name: Marks, dtype: float64

In [291]:
# 14. Generate descriptive statistics for all numeric columns.
df[['Marks','Srlno.','center_num']].describe()

              Marks        Srlno.    center_num
count  2.333162e+06  2.333162e+06  2.333162e+06
mean   2.171566e+02  2.902341e+02  3.224020e+05
std    1.662400e+02  2.171436e+02  1.049598e+05
min   -1.800000e+02  1.000000e+00  1.101010e+05
25%    8.700000e+01  1.240000e+02  2.602020e+05
50%    1.630000e+02  2.510000e+02  3.111190e+05
75%    3.130000e+02  4.080000e+02  4.122060e+05
max    7.200000e+02  1.968000e+03  9.914010e+05

In [292]:
# 15. Generate descriptive statistics for all columns, including non-numeric columns.
df[['center_name','city','state']].info()     # isme mujhe doubt hai brother

<class 'pandas.DataFrame'>
RangeIndex: 2333162 entries, 0 to 2333161
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   center_name  str
 1   city         str
 2   state        str
dtypes: str(3)
memory usage: 53.4 MB

In [293]:
# 16. Check whether the DataFrame contains any missing values.
df.isnull().sum()

state          0
city           0
center_name    0
center_num     0
Srlno.         0
Marks          0
dtype: int64

In [294]:
# 17. Count missing values in each column.

df.isnull().sum()

state          0
city           0
center_name    0
center_num     0
Srlno.         0
Marks          0
dtype: int64

In [295]:
# 18. Check whether the DataFrame contains duplicate rows.

df.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
2333157    False
2333158    False
2333159    False
2333160    False
2333161    False
Length: 2333162, dtype: bool

In [296]:
#19. Count the total number of duplicate rows.
df.duplicated().sum()

np.int64(0)

In [297]:
#20. Display the memory usage of the DataFrame.

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2333162 entries, 0 to 2333161
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   state        str
 1   city         str
 2   center_name  str
 3   center_num   int64
 4   Srlno.       int64
 5   Marks        int64
dtypes: int64(3), str(3)
memory usage: 106.8 MB

Level - 2

In [298]:
# 21. Display only the state column.

df['state']

0          ANDAMAN AND NICOBAR ISLANDS (UT)
1          ANDAMAN AND NICOBAR ISLANDS (UT)
2          ANDAMAN AND NICOBAR ISLANDS (UT)
3          ANDAMAN AND NICOBAR ISLANDS (UT)
4          ANDAMAN AND NICOBAR ISLANDS (UT)
                         ...
2333157                         WEST BENGAL
2333158                         WEST BENGAL
2333159                         WEST BENGAL
2333160                         WEST BENGAL
2333161                         WEST BENGAL
Name: state, Length: 2333162, dtype: str

In [299]:
# 22. Display only the city column.

df['city']

0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str

In [300]:
# 23. Display only the Marks column.
df['Marks']

0           46
1          226
2          449
3          424
4          222
          ...
2333157    279
2333158    102
2333159     14
2333160    179
2333161     91
Name: Marks, Length: 2333162, dtype: int64

In [301]:
# 24. Display state, city, and Marks.

df[['state','city','Marks']]

                                    state        city  Marks
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR     46
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    226
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    449
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    424
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    222
...                                   ...         ...    ...
2333157                       WEST BENGAL     KALYANI    279
2333158                       WEST BENGAL     KALYANI    102
2333159                       WEST BENGAL     KALYANI     14
2333160                       WEST BENGAL     KALYANI    179
2333161                       WEST BENGAL     KALYANI     91

[2333162 rows x 3 columns]

In [302]:
# 25. Display center_name and center_num.
df[['center_name','center_num']]

                      center_name  center_num
0        KENDRIYA VIDYALAYA NO. 1      110101
1        KENDRIYA VIDYALAYA NO. 1      110101
2        KENDRIYA VIDYALAYA NO. 1      110101
3        KENDRIYA VIDYALAYA NO. 1      110101
4        KENDRIYA VIDYALAYA NO. 1      110101
...                           ...         ...
2333157     CHAKDAHA MODEL SCHOOL      461312
2333158     CHAKDAHA MODEL SCHOOL      461312
2333159     CHAKDAHA MODEL SCHOOL      461312
2333160     CHAKDAHA MODEL SCHOOL      461312
2333161     CHAKDAHA MODEL SCHOOL      461312

[2333162 rows x 2 columns]

In [303]:
# 26. Display the first 20 rows using iloc.
df.iloc[0:20]

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222
5,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,6,181
6,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,7,115
7,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,8,127
8,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,9,88
9,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,10,77
10,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,11,322
11,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,12,434
12,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,13,101
13,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,14,155
14,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,15,134
15,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,16,58
16,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,17,222
17,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,18,133
18,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,19,184
19,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,20,104

In [304]:
# 27. Display rows 10 to 19 using iloc.
df.iloc[10:19]

,state,city,center_name,center_num,Srlno.,Marks
10,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,11,322
11,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,12,434
12,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,13,101
13,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,14,155
14,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,15,134
15,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,16,58
16,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,17,222
17,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,18,133
18,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,19,184

In [305]:
# 28. Display rows 50 to 59 using iloc.

df.iloc[50:60]  # kyki indexing mai last wala -1 hota hai isliye  60 liya

,state,city,center_name,center_num,Srlno.,Marks
50,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,51,40
51,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,52,104
52,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,53,175
53,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,54,150
54,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,55,51
55,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,56,680
56,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,57,98
57,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,58,68
58,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,59,374
59,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,60,145

In [306]:
# 29. Display the first 10 rows and first 3 columns using iloc.
df.iloc[0:10,0:3]

                              state        city               center_name
0  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
1  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
2  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
3  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
4  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
5  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
6  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
7  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
8  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
9  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1

In [307]:
# 30. Display rows 5 to 15 and columns state through Marks using iloc.

df.iloc[5:15,0:5]  #df.iloc[rows ka indexing,column ka indexing]

,state,city,center_name,center_num,Srlno.
5,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,6
6,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,7
7,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,8
8,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,9
9,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,10
10,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,11
11,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,12
12,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,13
13,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,14
14,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,15

In [308]:
# 31. Select the row with index 0 using iloc.
df.iloc[0]

state          ANDAMAN AND NICOBAR ISLANDS (UT)
city                                 PORT BLAIR
center_name            KENDRIYA VIDYALAYA NO. 1
center_num                               110101
Srlno.                                        1
Marks                                        46
Name: 0, dtype: object

In [309]:
# 32. Select rows with indexes 0, 5, and 10 using iloc.

df.iloc[[0,5,10]]

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
5,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,6,181
10,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,11,322

In [310]:

# 33. Select state and Marks for rows with indexes 0 through 9.

df.loc[ 0:9,['state','Marks']]   #humne 0 se 9 tak humne kiy hai and range adn dno column ko select kiya hai

                              state  Marks
0  ANDAMAN AND NICOBAR ISLANDS (UT)     46
1  ANDAMAN AND NICOBAR ISLANDS (UT)    226
2  ANDAMAN AND NICOBAR ISLANDS (UT)    449
3  ANDAMAN AND NICOBAR ISLANDS (UT)    424
4  ANDAMAN AND NICOBAR ISLANDS (UT)    222
5  ANDAMAN AND NICOBAR ISLANDS (UT)    181
6  ANDAMAN AND NICOBAR ISLANDS (UT)    115
7  ANDAMAN AND NICOBAR ISLANDS (UT)    127
8  ANDAMAN AND NICOBAR ISLANDS (UT)     88
9  ANDAMAN AND NICOBAR ISLANDS (UT)     77

In [311]:

# 34. Set SrIno as the DataFrame index.

df.index = df['Srlno.']           # iska mai sure nahihu chek krwana ahi sir
print(df)

                                   state        city  \
Srlno.
1       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
5       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                  ...         ...
135                          WEST BENGAL     KALYANI
136                          WEST BENGAL     KALYANI
137                          WEST BENGAL     KALYANI
138                          WEST BENGAL     KALYANI
139                          WEST BENGAL     KALYANI

                     center_name  center_num  Srlno.  Marks
Srlno.
1       KENDRIYA VIDYALAYA NO. 1      110101       1     46
2       KENDRIYA VIDYALAYA NO. 1      110101       2    226
3       KENDRIYA VIDYALAYA NO. 1      110101       3    449
4       KENDRIYA VIDYALAYA NO. 1      110101       4    424
5       KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                          ...         ...     ...    ...
135        CHAKDAHA MODEL SCHOOL      461312     135    279
136        CHAKDAHA MODEL SCHOOL      461312     136    102
137        CHAKDAHA MODEL SCHOOL      461312     137     14
138        CHAKDAHA MODEL SCHOOL      461312     138    179
139        CHAKDAHA MODEL SCHOOL      461312     139     91

[2333162 rows x 6 columns]

In [312]:
# 35. Reset the DataFrame index after setting SrIno as the index.

In [313]:
# 36. Select all columns except Marks.
df.index = range(len(df))    # ye bhi sir se condfirm krna hai doubt hai 
print(df)

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[2333162 rows x 6 columns]

In [314]:
# 37. Select all columns except state.
df.drop('state',axis= 1)         # expect matlb usko chuke ab jaise state chudke sb kuch axis = 0 ka maltb hota hai rows and axis = 1 ka matb hota hai columns

               city               center_name  center_num  Srlno.  Marks
0        PORT BLAIR  KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        PORT BLAIR  KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        PORT BLAIR  KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        PORT BLAIR  KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        PORT BLAIR  KENDRIYA VIDYALAYA NO. 1      110101       5    222
...             ...                       ...         ...     ...    ...
2333157     KALYANI     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     KALYANI     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     KALYANI     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     KALYANI     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     KALYANI     CHAKDAHA MODEL SCHOOL      461312     139     91

[2333162 rows x 5 columns]

In [315]:
# 38. Select state, city, center_name, and Marks.

df[['state','city','center_name','Marks']]

,state,city,center_name,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,222
...,...,...,...,...
2333157,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,279
2333158,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,102
2333159,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,14
2333160,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,179
2333161,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,91

In [316]:

# 39. Create a new DataFrame containing only city and Marks.

df2 = df[['city','Marks']]
print(df2)

               city  Marks
0        PORT BLAIR     46
1        PORT BLAIR    226
2        PORT BLAIR    449
3        PORT BLAIR    424
4        PORT BLAIR    222
...             ...    ...
2333157     KALYANI    279
2333158     KALYANI    102
2333159     KALYANI     14
2333160     KALYANI    179
2333161     KALYANI     91

[2333162 rows x 2 columns]

In [317]:
# 40. Create a copy of df containing state, city, and Marks.

df3 = df[['state','city','Marks']]

print(df3)

                                    state        city  Marks
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR     46
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    226
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    449
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    424
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    222
...                                   ...         ...    ...
2333157                       WEST BENGAL     KALYANI    279
2333158                       WEST BENGAL     KALYANI    102
2333159                       WEST BENGAL     KALYANI     14
2333160                       WEST BENGAL     KALYANI    179
2333161                       WEST BENGAL     KALYANI     91

[2333162 rows x 3 columns]

LEVEL - 3

In [318]:
#41. Display students who scored more than 650 marks.
df4 = df[df['Marks'] > 650]

print(df4)

                                    state        city  \
55       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
635      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
912      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1053                       ANDHRA PRADESH      GUNTUR
1055                       ANDHRA PRADESH      GUNTUR
...                                   ...         ...
2332661                       WEST BENGAL     KALYANI
2332713                       WEST BENGAL     KALYANI
2332738                       WEST BENGAL     KALYANI
2333094                       WEST BENGAL     KALYANI
2333115                       WEST BENGAL     KALYANI

                                               center_name  center_num  \
55                                KENDRIYA VIDYALAYA NO. 1      110101
635                DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102
912                DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102
1053                   LITTLE FLOWER ENGLISH MEDIUM SCHOOL      120101
1055                   LITTLE FLOWER ENGLISH MEDIUM SCHOOL      120101
...                                                    ...         ...
2332661  KATAGUNJ GOKULPUR ADARSHA SHIKSHAYATAN HIGH SC...      461310
2332713  KATAGUNJ GOKULPUR ADARSHA SHIKSHAYATAN HIGH SC...      461310
2332738  KATAGUNJ GOKULPUR ADARSHA SHIKSHAYATAN HIGH SC...      461310
2333094                              CHAKDAHA MODEL SCHOOL      461312
2333115                              CHAKDAHA MODEL SCHOOL      461312

         Srlno.  Marks
55           56    680
635         175    657
912         452    670
1053         29    656
1055         31    656
...         ...    ...
2332661      91    669
2332713     143    666
2332738     168    662
2333094      72    675
2333115      93    661

[28910 rows x 6 columns]

In [319]:
#42. Display students who scored less than 200 marks.

df5 = df[df['Marks']<200]
print(df5)

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
5        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
6        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
7        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
8        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333156                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
5        KENDRIYA VIDYALAYA NO. 1      110101       6    181
6        KENDRIYA VIDYALAYA NO. 1      110101       7    115
7        KENDRIYA VIDYALAYA NO. 1      110101       8    127
8        KENDRIYA VIDYALAYA NO. 1      110101       9     88
...                           ...         ...     ...    ...
2333156     CHAKDAHA MODEL SCHOOL      461312     134    130
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[1351340 rows x 6 columns]

In [328]:
#43. Display students who scored between 500 and 600 marks.

df6 = df[(df['Marks']>= 500) & (df['Marks']<=600)]
print(df6)

                                    state        city  \
27       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
32       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
37       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
40       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
104      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2332912                       WEST BENGAL     KALYANI
2332929                       WEST BENGAL     KALYANI
2333057                       WEST BENGAL     KALYANI
2333071                       WEST BENGAL     KALYANI
2333148                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
27       KENDRIYA VIDYALAYA NO. 1      110101      28    544
32       KENDRIYA VIDYALAYA NO. 1      110101      33    511
37       KENDRIYA VIDYALAYA NO. 1      110101      38    559
40       KENDRIYA VIDYALAYA NO. 1      110101      41    580
104      KENDRIYA VIDYALAYA NO. 1      110101     105    579
...                           ...         ...     ...    ...
2332912        GARDEN HIGH SCHOOL      461311      68    532
2332929        GARDEN HIGH SCHOOL      461311      85    563
2333057     CHAKDAHA MODEL SCHOOL      461312      35    514
2333071     CHAKDAHA MODEL SCHOOL      461312      49    580
2333148     CHAKDAHA MODEL SCHOOL      461312     126    592

[130040 rows x 6 columns]

In [330]:
#44. Display students who scored exactly 720 marks.
df7 = df[df['Marks']==720]
print(df7)

                  state         city  \
12528    ANDHRA PRADESH      NELLORE
18809    ANDHRA PRADESH   VIJAYAWADA
19979    ANDHRA PRADESH   VIJAYAWADA
21180    ANDHRA PRADESH   VIJAYAWADA
126184            BIHAR    MADHUBANI
...                 ...          ...
2153326   UTTAR PRADESH      LUCKNOW
2201862     UTTARAKHAND     HALDWANI
2260412     WEST BENGAL      KOLKATA
2279145     WEST BENGAL  MURSHIDABAD
2314725     WEST BENGAL     SILIGURI

                                               center_name  center_num  \
12528           PADMAVATHI VIDYALAYA SULLURPETA NELLORE AP      120304
18809    POTTI SRIRAMULU CHALAVADI MALLIKARJUNA RAO COL...      120501
19979                    KAKARAPARTI BHAVANARAYANA COLLEGE      120503
21180      DHANEKULA INSTITUTE OF ENGINEERING & TECHNOLOGY      120504
126184                                           POLE STAR      150402
...                                                    ...         ...
2153326                             S.D.S.N. MAHAVIDYALAYA      440801
2201862               SRI GURU TEG BAHADUR SR. SEC. SCHOOL      450201
2260412            RCC INSTITUTE OF INFORMATION TECHNOLOGY      460806
2279145                                GUIDANCE FOUNDATION      461502
2314725                                       D.A.V SCHOOL      460902

         Srlno.  Marks
12528       201    720
18809      1150    720
19979       130    720
21180       383    720
126184      621    720
...         ...    ...
2153326     959    720
2201862     321    720
2260412     485    720
2279145     497    720
2314725      58    720

[61 rows x 6 columns]

In [333]:
#45. Display students who scored 0 marks.

df8 = df[df['Marks']==0]

print(df8)

                  state        city                   center_name  center_num  \
4796     ANDHRA PRADESH      GUNTUR   DR K L PRASAD PUBLIC SCHOOL      120108
5211     ANDHRA PRADESH     KURNOOL        MONTESSORI HIGH SCHOOL      120201
5437     ANDHRA PRADESH     KURNOOL        MONTESSORI HIGH SCHOOL      120201
7381     ANDHRA PRADESH     KURNOOL    ST. JOSEPHS DEGREE COLLEGE      120203
9035     ANDHRA PRADESH     KURNOOL             THE ATHENA SCHOOL      120205
...                 ...         ...                           ...         ...
2322802     WEST BENGAL     BANKURA          BANKURA ZILLA SCHOOL      461005
2323493     WEST BENGAL     BANKURA         BANKUR BANGA VIDYALAY      461007
2324669     WEST BENGAL     BANKURA    JAWAHAR NAVODAYA VIDYALAYA      461010
2325248     WEST BENGAL     BANKURA             DAV PUBLIC SCHOOL      461011
2326253     WEST BENGAL  JALPAIGURI  ARMY PUBLIC SCHOOL BINNAGURI      461201

         Srlno.  Marks
4796        141      0
5211        254      0
5437        480      0
7381        306      0
9035        550      0
...         ...    ...
2322802     216      0
2323493      69      0
2324669     219      0
2325248     561      0
2326253     642      0

[2259 rows x 6 columns]

In [334]:
#46. Display students whose Marks are greater than or equal to 600.

df9 = df[df['Marks']>= 600]
print(df9)

                                    state        city  \
55       ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
334      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
635      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
912      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
981      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2332731                       WEST BENGAL     KALYANI
2332738                       WEST BENGAL     KALYANI
2332739                       WEST BENGAL     KALYANI
2333094                       WEST BENGAL     KALYANI
2333115                       WEST BENGAL     KALYANI

                                               center_name  center_num  \
55                                KENDRIYA VIDYALAYA NO. 1      110101
334                               KENDRIYA VIDYALAYA NO. 1      110101
635                DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102
912                DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY      110102
981               GOVERNMENT MODEL SENIOR SECONDARY SCHOOL      110103
...                                                    ...         ...
2332731  KATAGUNJ GOKULPUR ADARSHA SHIKSHAYATAN HIGH SC...      461310
2332738  KATAGUNJ GOKULPUR ADARSHA SHIKSHAYATAN HIGH SC...      461310
2332739  KATAGUNJ GOKULPUR ADARSHA SHIKSHAYATAN HIGH SC...      461310
2333094                              CHAKDAHA MODEL SCHOOL      461312
2333115                              CHAKDAHA MODEL SCHOOL      461312

         Srlno.  Marks
55           56    680
334         335    620
635         175    657
912         452    670
981          60    648
...         ...    ...
2332731     161    614
2332738     168    662
2332739     169    634
2333094      72    675
2333115      93    661

[81550 rows x 6 columns]

In [336]:
#47. Display students whose Marks are less than or equal to 300.
df10 = df[df['Marks']<= 300]
print(df10)

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
5        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
6        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
5        KENDRIYA VIDYALAYA NO. 1      110101       6    181
6        KENDRIYA VIDYALAYA NO. 1      110101       7    115
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[1715186 rows x 6 columns]

In [337]:
#48. Display students whose Marks are not equal to 0.

df11 = df[df['Marks']!= 0]
print(df11)

                                    state        city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

                      center_name  center_num  Srlno.  Marks
0        KENDRIYA VIDYALAYA NO. 1      110101       1     46
1        KENDRIYA VIDYALAYA NO. 1      110101       2    226
2        KENDRIYA VIDYALAYA NO. 1      110101       3    449
3        KENDRIYA VIDYALAYA NO. 1      110101       4    424
4        KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                           ...         ...     ...    ...
2333157     CHAKDAHA MODEL SCHOOL      461312     135    279
2333158     CHAKDAHA MODEL SCHOOL      461312     136    102
2333159     CHAKDAHA MODEL SCHOOL      461312     137     14
2333160     CHAKDAHA MODEL SCHOOL      461312     138    179
2333161     CHAKDAHA MODEL SCHOOL      461312     139     91

[2330903 rows x 6 columns]

In [339]:
#49. Display students from a particular state.

df12 = df[df['state'] == 'CHHATTISGARH']

print(df12)

               state               city                     center_name  \
253641  CHHATTISGARH  BHILAI NAGAR/DURG   SHRI SHANKARACHARYA VIDYALAYA
253642  CHHATTISGARH  BHILAI NAGAR/DURG   SHRI SHANKARACHARYA VIDYALAYA
253643  CHHATTISGARH  BHILAI NAGAR/DURG   SHRI SHANKARACHARYA VIDYALAYA
253644  CHHATTISGARH  BHILAI NAGAR/DURG   SHRI SHANKARACHARYA VIDYALAYA
253645  CHHATTISGARH  BHILAI NAGAR/DURG   SHRI SHANKARACHARYA VIDYALAYA
...              ...                ...                             ...
297877  CHHATTISGARH       MANENDRAGARH  DELHI WORLD PUBLIC SCHOOL MDGR
297878  CHHATTISGARH       MANENDRAGARH  DELHI WORLD PUBLIC SCHOOL MDGR
297879  CHHATTISGARH       MANENDRAGARH  DELHI WORLD PUBLIC SCHOOL MDGR
297880  CHHATTISGARH       MANENDRAGARH  DELHI WORLD PUBLIC SCHOOL MDGR
297881  CHHATTISGARH       MANENDRAGARH  DELHI WORLD PUBLIC SCHOOL MDGR

        center_num  Srlno.  Marks
253641      170101       1     58
253642      170101       2    374
253643      170101       3     98
253644      170101       4    221
253645      170101       5    512
...            ...     ...    ...
297877      171901     521    120
297878      171901     522    392
297879      171901     523    120
297880      171901     524    361
297881      171901     525    321

[44241 rows x 6 columns]

In [345]:
#50. Display students from a particular city.

df13 = df[df['city'] == 'PORT BLAIR']
print(df13)

                                 state        city  \
0     ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1     ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2     ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3     ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4     ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                ...         ...
1020  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1021  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1022  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1023  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1024  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR

                                   center_name  center_num  Srlno.  Marks
0                     KENDRIYA VIDYALAYA NO. 1      110101       1     46
1                     KENDRIYA VIDYALAYA NO. 1      110101       2    226
2                     KENDRIYA VIDYALAYA NO. 1      110101       3    449
3                     KENDRIYA VIDYALAYA NO. 1      110101       4    424
4                     KENDRIYA VIDYALAYA NO. 1      110101       5    222
...                                        ...         ...     ...    ...
1020  GOVERNMENT MODEL SENIOR SECONDARY SCHOOL      110103      99    264
1021  GOVERNMENT MODEL SENIOR SECONDARY SCHOOL      110103     100     42
1022  GOVERNMENT MODEL SENIOR SECONDARY SCHOOL      110103     101    334
1023  GOVERNMENT MODEL SENIOR SECONDARY SCHOOL      110103     102    238
1024  GOVERNMENT MODEL SENIOR SECONDARY SCHOOL      110103     103    145

[1025 rows x 6 columns]

In [ ]:
#51. Display students from a particular examination centre.

In [ ]:
#52. Display students not belonging to a particular state.

In [ ]:
#53. Display students whose Marks are 600, 610, or 620.

In [ ]:
#54. Display students whose city starts with the letter A.

In [ ]:
#55. Display students whose city ends with the letter A.

In [ ]:
#56. Display students whose city contains the word 'pur'.

In [ ]:
#57. Display students whose center_name contains 'Public School'.

In [ ]:
#58. Display students whose center_name contains the word 'School'.

In [ ]:
#59. Display students whose state starts with a specific letter.

In [ ]:
#60. Display students whose state name contains a specific substring.

LEVEL - 4