In [1]:
import pandas as pd

300_Question_of_Pyth0n_Pandas_Data_Frame

Level - 1

In [2]:
# 1. Load the NEET dataset into a pandas DataFrame named df.

df = pd.read_csv('all_neet_marks_2607.csv')

In [3]:
# 2. Display the first 5 rows of the DataFrame.

df.head()

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222

In [4]:
# 3. Display the last 5 rows of the DataFrame.

df.tail()

,state,city,center_name,center_num,Srlno.,Marks
2333157,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,135,279
2333158,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,136,102
2333159,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,137,14
2333160,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,138,179
2333161,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,139,91

In [5]:
# 4. Display the first 10 rows of the DataFrame.

df.head(10)

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222
5,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,6,181
6,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,7,115
7,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,8,127
8,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,9,88
9,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,10,77

In [6]:
# 5. Display the last 10 rows of the DataFrame.

df.tail(10)

,state,city,center_name,center_num,Srlno.,Marks
2333152,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,130,90
2333153,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,131,250
2333154,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,132,130
2333155,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,133,55
2333156,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,134,130
2333157,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,135,279
2333158,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,136,102
2333159,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,137,14
2333160,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,138,179
2333161,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,139,91

In [7]:
# 6. Display the shape of the DataFrame.

df.shape

(2333162, 6)

In [8]:
# 7. Display the number of rows in the DataFrame.

df.shape[0]

2333162

In [9]:
#8. Display the number of columns in the DataFrame.
df.shape[1]

6

In [10]:
#9. Display all column names.
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [11]:
#10. Display the DataFrame index.

df.index

RangeIndex(start=0, stop=2333162, step=1)

In [12]:
# 11. Display the data types of all columns.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2333162 entries, 0 to 2333161
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   state        str
 1   city         str
 2   center_name  str
 3   center_num   int64
 4   Srlno.       int64
 5   Marks        int64
dtypes: int64(3), str(3)
memory usage: 106.8 MB

In [13]:
# 12. Generate a concise summary of the DataFrame using info().

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2333162 entries, 0 to 2333161
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   state        str
 1   city         str
 2   center_name  str
 3   center_num   int64
 4   Srlno.       int64
 5   Marks        int64
dtypes: int64(3), str(3)
memory usage: 106.8 MB

In [14]:
# 13. Generate descriptive statistics for the Marks column.
df['Marks'].describe()

count    2.333162e+06
mean     2.171566e+02
std      1.662400e+02
min     -1.800000e+02
25%      8.700000e+01
50%      1.630000e+02
75%      3.130000e+02
max      7.200000e+02
Name: Marks, dtype: float64

In [15]:
# 14. Generate descriptive statistics for all numeric columns.
df[['Marks','Srlno.','center_num']].describe()

              Marks        Srlno.    center_num
count  2.333162e+06  2.333162e+06  2.333162e+06
mean   2.171566e+02  2.902341e+02  3.224020e+05
std    1.662400e+02  2.171436e+02  1.049598e+05
min   -1.800000e+02  1.000000e+00  1.101010e+05
25%    8.700000e+01  1.240000e+02  2.602020e+05
50%    1.630000e+02  2.510000e+02  3.111190e+05
75%    3.130000e+02  4.080000e+02  4.122060e+05
max    7.200000e+02  1.968000e+03  9.914010e+05

In [16]:
# 15. Generate descriptive statistics for all columns, including non-numeric columns.
df[['center_name','city','state']].info()     # isme mujhe doubt hai brother

<class 'pandas.DataFrame'>
RangeIndex: 2333162 entries, 0 to 2333161
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   center_name  str
 1   city         str
 2   state        str
dtypes: str(3)
memory usage: 53.4 MB

In [17]:
# 16. Check whether the DataFrame contains any missing values.
df.isnull().sum()

state          0
city           0
center_name    0
center_num     0
Srlno.         0
Marks          0
dtype: int64

In [18]:
# 17. Count missing values in each column.

df.isnull().sum()

state          0
city           0
center_name    0
center_num     0
Srlno.         0
Marks          0
dtype: int64

In [19]:
# 18. Check whether the DataFrame contains duplicate rows.

df.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
2333157    False
2333158    False
2333159    False
2333160    False
2333161    False
Length: 2333162, dtype: bool

In [20]:
#19. Count the total number of duplicate rows.
df.duplicated().sum()

np.int64(0)

In [21]:
#20. Display the memory usage of the DataFrame.

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2333162 entries, 0 to 2333161
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   state        str
 1   city         str
 2   center_name  str
 3   center_num   int64
 4   Srlno.       int64
 5   Marks        int64
dtypes: int64(3), str(3)
memory usage: 106.8 MB

Level - 2

In [23]:
# 21. Display only the state column.

df['state']

0          ANDAMAN AND NICOBAR ISLANDS (UT)
1          ANDAMAN AND NICOBAR ISLANDS (UT)
2          ANDAMAN AND NICOBAR ISLANDS (UT)
3          ANDAMAN AND NICOBAR ISLANDS (UT)
4          ANDAMAN AND NICOBAR ISLANDS (UT)
                         ...
2333157                         WEST BENGAL
2333158                         WEST BENGAL
2333159                         WEST BENGAL
2333160                         WEST BENGAL
2333161                         WEST BENGAL
Name: state, Length: 2333162, dtype: str

In [24]:
# 22. Display only the city column.

df['city']

0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str

In [25]:
# 23. Display only the Marks column.
df['Marks']

0           46
1          226
2          449
3          424
4          222
          ...
2333157    279
2333158    102
2333159     14
2333160    179
2333161     91
Name: Marks, Length: 2333162, dtype: int64

In [28]:
# 24. Display state, city, and Marks.

df[['state','city','Marks']]

                                    state        city  Marks
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR     46
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    226
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    449
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    424
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    222
...                                   ...         ...    ...
2333157                       WEST BENGAL     KALYANI    279
2333158                       WEST BENGAL     KALYANI    102
2333159                       WEST BENGAL     KALYANI     14
2333160                       WEST BENGAL     KALYANI    179
2333161                       WEST BENGAL     KALYANI     91

[2333162 rows x 3 columns]

In [29]:
# 25. Display center_name and center_num.
df[['center_name','center_num']]

                      center_name  center_num
0        KENDRIYA VIDYALAYA NO. 1      110101
1        KENDRIYA VIDYALAYA NO. 1      110101
2        KENDRIYA VIDYALAYA NO. 1      110101
3        KENDRIYA VIDYALAYA NO. 1      110101
4        KENDRIYA VIDYALAYA NO. 1      110101
...                           ...         ...
2333157     CHAKDAHA MODEL SCHOOL      461312
2333158     CHAKDAHA MODEL SCHOOL      461312
2333159     CHAKDAHA MODEL SCHOOL      461312
2333160     CHAKDAHA MODEL SCHOOL      461312
2333161     CHAKDAHA MODEL SCHOOL      461312

[2333162 rows x 2 columns]

In [40]:
# 26. Display the first 20 rows using iloc.
df.iloc[0:20]

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222
5,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,6,181
6,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,7,115
7,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,8,127
8,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,9,88
9,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,10,77
10,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,11,322
11,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,12,434
12,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,13,101
13,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,14,155
14,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,15,134
15,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,16,58
16,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,17,222
17,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,18,133
18,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,19,184
19,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,20,104

In [41]:
# 27. Display rows 10 to 19 using iloc.
df.iloc[10:19]

,state,city,center_name,center_num,Srlno.,Marks
10,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,11,322
11,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,12,434
12,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,13,101
13,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,14,155
14,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,15,134
15,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,16,58
16,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,17,222
17,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,18,133
18,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,19,184

In [ ]:
# 28. Display rows 50 to 59 using iloc.

df.iloc[50:60]  # kyki indexing mai last wala -1 hota hai isliye  60 liya

,state,city,center_name,center_num,Srlno.,Marks
50,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,51,40
51,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,52,104
52,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,53,175
53,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,54,150
54,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,55,51
55,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,56,680
56,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,57,98
57,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,58,68
58,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,59,374
59,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,60,145

In [45]:
# 29. Display the first 10 rows and first 3 columns using iloc.
df.iloc[0:10,0:3]

                              state        city               center_name
0  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
1  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
2  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
3  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
4  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
5  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
6  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
7  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
8  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
9  ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1

In [ ]:
# 30. Display rows 5 to 15 and columns state through Marks using iloc.

df.iloc[5:15,0:5]  #df.iloc[rows ka indexing,column ka indexing]

,state,city,center_name,center_num,Srlno.
5,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,6
6,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,7
7,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,8
8,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,9
9,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,10
10,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,11
11,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,12
12,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,13
13,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,14
14,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,15

In [ ]:
# 31. Select the row with index 0 using iloc.

In [ ]:
# 32. Select rows with indexes 0, 5, and 10 using iloc.

In [ ]:

# 33. Select state and Marks for rows with indexes 0 through 9.

In [ ]:

# 34. Set SrIno as the DataFrame index.

In [ ]:
# 35. Reset the DataFrame index after setting SrIno as the index.

In [22]:
# 36. Select all columns except Marks.

In [ ]:
# 37. Select all columns except state.

In [ ]:
# 38. Select state, city, center_name, and Marks.

In [ ]:

# 39. Create a new DataFrame containing only city and Marks.

In [ ]:
# 40. Create a copy of df containing state, city, and Marks.