Revision of pands in home

In [1]:
import pandas as pd 
import  numpy as np

In [2]:
df =pd.read_csv('all_neet_marks_2607.csv')

In [15]:
# Marks 600 se greater (> 600) wale saare students nikalo.
 
df.loc[df['Marks'] > 600 ]

,state,city,center_name,center_num,Srlno.,Marks
55,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,56,680
334,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,335,620
635,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY,110102,175,657
912,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,DR B R AMBEDKAR INSTITUTE OF TECHNOLOGY,110102,452,670
981,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,GOVERNMENT MODEL SENIOR SECONDARY SCHOOL,110103,60,648
...,...,...,...,...,...,...
2332731,WEST BENGAL,KALYANI,KATAGUNJ GOKULPUR ADARSHA SHIKSHAYATAN HIGH SC...,461310,161,614
2332738,WEST BENGAL,KALYANI,KATAGUNJ GOKULPUR ADARSHA SHIKSHAYATAN HIGH SC...,461310,168,662
2332739,WEST BENGAL,KALYANI,KATAGUNJ GOKULPUR ADARSHA SHIKSHAYATAN HIGH SC...,461310,169,634
2333094,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,72,675
2333115,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,93,661

In [16]:
# CHHATTISGARH state ke aur Marks 500 se greater (> 500) wale saare students nikalo.

df.loc[(df[' state'] == 'CHHATTISGARH') & (df['Marks'] > 500) ]

,state,city,center_name,center_num,Srlno.,Marks
253645,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,5,512
253646,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,6,595
253647,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,7,502
253653,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,13,658
253668,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,28,618
...,...,...,...,...,...,...
297855,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,499,561
297860,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,504,532
297867,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,511,585
297868,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,512,528
297872,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,516,550

In [17]:
df.columns

Index([' state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [18]:
# q3 NEET dataset df mein Marks ke basis par top 10 students nikalo.

df_3 = df.sort_values( by = 'Marks', ascending=False).head(10)

print(df_3)

               state                        city  \
375023       GUJARAT                   AHMEDABAD
1298400  MAHARASHTRA                      NAGPUR
1618426    RAJASTHAN                       SIKAR
1442827    RAJASTHAN                      JAIPUR
1672212   TAMIL NADU                     CHENNAI
801098        KERALA                    ANGAMALY
1665288   TAMIL NADU                     CHENNAI
1619146    RAJASTHAN                       SIKAR
1428015       PUNJAB  SAHIBZADA AJIT SINGH NAGAR
210950         BIHAR                       PATNA

                                               center_name  center_num  \
375023                       SHREE NARAYANA CENTRAL SCHOOL      220106
1298400            BHAVANS BHAGWANDAS PUROHIT VIDYA MANDIR      311102
1618426                        YASH PUBLIC SR. SEC. SCHOOL      392346
1442827          UCCH MADHYMIK BALIKA ADARSH VIDHYA MANDIR      390302
1672212     SRI BALA VIDYALAYA PERAMBUR CHENNAI TAMIL NADU      410117
801098                        CHINMAYA VIDYALAYA VADUTHALA      280202
1665288  ST.PETERS INSTITUTE OF HIGHER EDUCATION AND RE...      410107
1619146                        VIDYA BHARATI PUBLIC SCHOOL      392349
1428015      GOVT MODEL HIGH SCHOOL SECTOR 29-A CHANDIGARH      381406
210950                          PM SHRI KENDRIYA VIDYALAYA      150245

         Srlno.  Marks
375023      278    720
1298400     293    720
1618426     301    720
1442827     433    720
1672212     208    720
801098      285    720
1665288     332    720
1619146      94    720
1428015     196    720
210950      409    720

In [20]:
# 4 NEET dataset df mein har state ka average Marks nikalo.

df.groupby(' state').agg({'Marks' : 'mean'})

                                       Marks
 state
ANDAMAN AND NICOBAR ISLANDS (UT)  192.737561
ANDHRA PRADESH                    260.971024
ARUNACHAL PRADESH                 162.896942
ASSAM                             190.937931
BIHAR                             188.584457
CHANDIGARH(UT)                    304.816714
CHHATTISGARH                      185.636084
DADRA AND NAGAR HAVELI (UT)       221.932063
DAMAN AND DIU (UT)                180.239272
DELHI                             256.136435
GOA                               196.671805
GUJARAT                           245.138410
HARYANA                           261.349810
HIMACHAL PRADESH                  225.685638
JAMMU AND KASHMIR                 205.413497
JHARKHAND                         207.912365
KARNATAKA                         219.465622
KERALA                            235.698966
LADAKH(UT)                        166.485315
LAKSHADWEEP (UT)                  150.119760
MADHYA PRADESH                    174.264999
MAHARASHTRA                       202.281102
MANIPUR                           200.175833
MEGHALAYA                         156.409369
MIZORAM                           155.139354
NAGALAND                          172.792713
ODISHA                            204.629606
OUTSIDE-INDIA                     250.775789
PUDUCHERRY(UT)                    196.230637
PUNJAB                            228.662364
RAJASTHAN                         280.354518
SIKKIM                            179.342798
TAMIL NADU                        220.351702
TELANGANA                         222.757729
TRIPURA                           178.175363
UTTAR PRADESH                     192.716034
UTTARAKHAND                       216.313793
WEST BENGAL                       219.478585

In [ ]:
# 5 Har state ke liye 3 cheezein nikalo:
# Students ki total count
# Average Marks
# Maximum Marks

df.groupby('state').agg({'Marks' : ['count','mean','max']})

                                   Marks
                                   count        mean  max
state
ANDAMAN AND NICOBAR ISLANDS (UT)    1025  192.737561  680
ANDHRA PRADESH                     63846  260.971024  720
ARUNACHAL PRADESH                   4774  162.896942  705
ASSAM                              44273  190.937931  715
BIHAR                             136193  188.584457  720
CHANDIGARH(UT)                      3530  304.816714  715
CHHATTISGARH                       44241  185.636084  711
DADRA AND NAGAR HAVELI (UT)         1207  221.932063  692
DAMAN AND DIU (UT)                   769  180.239272  665
DELHI                              66090  256.136435  720
GOA                                 4930  196.671805  697
GUJARAT                            86952  245.138410  720
HARYANA                            54864  261.349810  716
HIMACHAL PRADESH                   19064  225.685638  711
JAMMU AND KASHMIR                  47553  205.413497  715
JHARKHAND                          34404  207.912365  720
KARNATAKA                         150897  219.465622  720
KERALA                            138546  235.698966  720
LADAKH(UT)                           715  166.485315  533
LAKSHADWEEP (UT)                     167  150.119760  609
MADHYA PRADESH                    130238  174.264999  715
MAHARASHTRA                       275245  202.281102  720
MANIPUR                             8946  200.175833  672
MEGHALAYA                           3757  156.409369  692
MIZORAM                             2569  155.139354  559
NAGALAND                            3705  172.792713  648
ODISHA                             64318  204.629606  715
OUTSIDE-INDIA                       4750  250.775789  710
PUDUCHERRY(UT)                      5810  196.230637  690
PUNJAB                             26573  228.662364  720
RAJASTHAN                         193130  280.354518  720
SIKKIM                              1444  179.342798  656
TAMIL NADU                        153704  220.351702  720
TELANGANA                          77892  222.757729  715
TRIPURA                             5098  178.175363  720
UTTAR PRADESH                     332631  192.716034  720
UTTARAKHAND                        21989  216.313793  720
WEST BENGAL                       117323  219.478585  720

In [ ]:
#6 Har center_name ka average Marks nikalo aur identify karo ki sabse zyada average Marks kis center ka hai.

df_6 = df.groupby('center_name').agg({'Marks': 'mean'})

df_6 = df_6.sort_values(by='Marks', ascending=False).head(1)

print(df_6)

                                  Marks
center_name
DELHI PUBLIC SCHOOL, REWARI  406.340909

In [ ]:
# 7 Marks column mein missing (NaN) values kitni hain, aur un rows ko identify karo.

# Marks column mein kitni missing (NaN) values hain
print(df['Marks'].isnull().sum())

# Missing Marks wali saari rows identify karo
print(df.loc[df['Marks'].isnull()])

0
Empty DataFrame
Columns: [state, city, center_name, center_num, Srlno., Marks]
Index: []

In [ ]:
# 8 NEET dataset df mein duplicate rows identify karo aur duplicates ko remove karo, lekin har duplicate ki first occurrence ko keep karo.

df.duplicated().sum()
df.drop_duplicates()
df.drop_duplicates(keep='first')    # first duplicate row ko rakhta hai, baaki duplicate hata deta hai

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222
...,...,...,...,...,...,...
2333157,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,135,279
2333158,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,136,102
2333159,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,137,14
2333160,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,138,179
2333161,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,139,91

In [ ]:
# 9 NEET dataset df mein sirf valid Marks wale students nikalo, jahan Marks > 0 aur Marks <= 720 h

df.loc[(df['Marks'] > 0 ) & (df['Marks'] <= 720)]

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222
...,...,...,...,...,...,...
2333157,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,135,279
2333158,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,136,102
2333159,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,137,14
2333160,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,138,179
2333161,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,139,91

In [ ]:
# 10  NEET dataset df mein Marks ke basis par ek naya column Category banao:

# Marks > 500 → High
# Marks >= 300 and Marks <= 500 → Medium
# Marks < 300 → Low

df['High_Medium_Low'] = np.where(df['Marks'] > 500,'High',np.where(df['Marks'] >= 300,'Medium','Low'))

print(df['High_Medium_Low'])

0             Low
1             Low
2          Medium
3          Medium
4             Low
            ...
2333157       Low
2333158       Low
2333159       Low
2333160       Low
2333161       Low
Name: High_Medium_Low, Length: 2333162, dtype: str

In [ ]:
# quesiton acche se likhr kr
# 🟢 Q11 — State-wise High/Medium/Low Students

# NEET dataset df mein har state ke andar kitne students High, Medium aur Low category mein hain, ye count karo.

# Category already High_Medium_Low column mein hai:

# High → Marks > 500
# Medium → Marks 300–500
# Low → Marks < 300

df_11 = df.groupby(['state','High_Medium_Low']).agg({'Marks' : 'count'})

print(df_11)

                                                  Marks
state                            High_Medium_Low
ANDAMAN AND NICOBAR ISLANDS (UT) High                28
                                 Low                831
                                 Medium             166
ANDHRA PRADESH                   High              7860
                                 Low              39368
...                                                 ...
UTTARAKHAND                      Low              16366
                                 Medium            3898
WEST BENGAL                      High             11601
                                 Low              85609
                                 Medium           20113

[114 rows x 1 columns]

In [ ]:
# 🟢 Q12 — State Average Marks Comparison

# NEET dataset df mein har state ka average Marks calculate karo aur us average ko original df mein ek naye column State_Avg_Marks ke roop mein add karo.

state_Avg = df.groupby('state').agg({'Marks' : 'mean'}).reset_index()

state_Avg = state_Avg.rename(columns ={'Marks' : 'State_Avg_Marks'})

df = df.merge(state_Avg, on = 'state' , how = 'inner')

print(df[['state','Marks','State_Avg_Marks']])

                                    state  Marks  State_Avg_Marks
0        ANDAMAN AND NICOBAR ISLANDS (UT)     46       192.737561
1        ANDAMAN AND NICOBAR ISLANDS (UT)    226       192.737561
2        ANDAMAN AND NICOBAR ISLANDS (UT)    449       192.737561
3        ANDAMAN AND NICOBAR ISLANDS (UT)    424       192.737561
4        ANDAMAN AND NICOBAR ISLANDS (UT)    222       192.737561
...                                   ...    ...              ...
2333157                       WEST BENGAL    279       219.478585
2333158                       WEST BENGAL    102       219.478585
2333159                       WEST BENGAL     14       219.478585
2333160                       WEST BENGAL    179       219.478585
2333161                       WEST BENGAL     91       219.478585

[2333162 rows x 3 columns]

In [ ]:
# 🟢 Q13 — Above / Below State Average

# NEET dataset df mein ek naya column Performance banao.

# Marks ko State_Avg_Marks se compare karo:

# Marks > State_Avg_Marks → Above Average
# Marks < State_Avg_Marks → Below Average
# Marks == State_Avg_Marks → Average

df['Performance']  =  np.where(df['Marks'] > df['State_Avg_Marks'],'Above_Average',np.where(df['Marks'] < df['State_Avg_Marks'],'Below_Average','Average'))

print(df['Performance'])

0          Below_Average
1          Above_Average
2          Above_Average
3          Above_Average
4          Above_Average
               ...
2333157    Above_Average
2333158    Below_Average
2333159    Below_Average
2333160    Below_Average
2333161    Below_Average
Name: Performance, Length: 2333162, dtype: str

In [ ]:
# 🟢 Q14 — Centre-wise Contribution

# NEET dataset df mein har center_name ke total candidates ka percentage contribution calculate karo.

# 🎯 Output mein ye 3 cheezein honi chahiye:
# center_name
# Candidates → us centre ke total students
# Contribution → total candidates mein us centre ka percentage


total_candidates = df.groupby('center_name').agg({'Marks' : 'count'}).reset_index()
# Har centre mein kitne candidates hain, ye count kiya

total_candidates = total_candidates.rename(columns= {'Marks' : 'Candidates'})
# Marks column ka naam Candidates kar diya

total = total_candidates['Candidates'].sum()
# Saare centres ke candidates ko add karke total candidates nikale

total_candidates['Contribution'] = (total_candidates['Candidates'] / total) * 100
# Har centre ka total candidates mein percentage nikala

print(total_candidates['Contribution'])
# Har centre ka contribution percentage print kiya

0       0.007158
1       0.041703
2       0.014744
3       0.040460
4       0.074834
          ...
4395    0.016115
4396    0.020101
4397    0.010158
4398    0.020230
4399    0.017230
Name: Contribution, Length: 4400, dtype: float64

In [ ]:
# 🟢 Q15 — State-wise Highest Scorer
# Har state ka highest scorer find karo.
# Output mein ye columns hone chahiye:
# state, Marks, city, center_name

# Hint:
# groupby() + max() se maximum Marks identify karo
# phir original df se us student ki complete row nikalo.


df_15 = df.groupby('state').agg({'Marks': 'max'}).reset_index()
# Har state ka maximum Marks nikala

df_15 = df.merge(df_15, on='state', how='inner')
# Maximum Marks ko original df ke saath state ke basis par merge kiya

df_15 = df_15.loc[df_15['Marks_x'] == df_15['Marks_y']]
# Jinke original Marks state ke maximum Marks ke equal hain, sirf unko rakha

print(df_15[['state', 'Marks_x', 'city', 'center_name']])
# State, highest Marks, city aur centre ka output dikhaya

                                    state  Marks_x         city  \
55       ANDAMAN AND NICOBAR ISLANDS (UT)      680   PORT BLAIR
12528                      ANDHRA PRADESH      720      NELLORE
18809                      ANDHRA PRADESH      720   VIJAYAWADA
19979                      ANDHRA PRADESH      720   VIJAYAWADA
21180                      ANDHRA PRADESH      720   VIJAYAWADA
...                                   ...      ...          ...
2153326                     UTTAR PRADESH      720      LUCKNOW
2201862                       UTTARAKHAND      720     HALDWANI
2260412                       WEST BENGAL      720      KOLKATA
2279145                       WEST BENGAL      720  MURSHIDABAD
2314725                       WEST BENGAL      720     SILIGURI

                                               center_name
55                                KENDRIYA VIDYALAYA NO. 1
12528           PADMAVATHI VIDYALAYA SULLURPETA NELLORE AP
18809    POTTI SRIRAMULU CHALAVADI MALLIKARJUNA RAO COL...
19979                    KAKARAPARTI BHAVANARAYANA COLLEGE
21180      DHANEKULA INSTITUTE OF ENGINEERING & TECHNOLOGY
...                                                    ...
2153326                             S.D.S.N. MAHAVIDYALAYA
2201862               SRI GURU TEG BAHADUR SR. SEC. SCHOOL
2260412            RCC INSTITUTE OF INFORMATION TECHNOLOGY
2279145                                GUIDANCE FOUNDATION
2314725                                       D.A.V SCHOOL

[109 rows x 4 columns]

In [ ]:
# 🟢 Q16 — State-wise Candidate Count
# Har state mein total kitne candidates hain, ye find karo.
# Output mein state aur Candidates columns hone chahiye.
# Candidates ko descending order mein sort karo.
# Top 10 states show karo.

df_16 = df.groupby('state').agg({'Marks' : 'count'}).reset_index()
df_16 = df_16.rename(columns= {'Marks' : 'Candidates'})
df_16 =  df_16.sort_values(by = 'Candidates',ascending=False).head(10)
print(df_16)

             state  Candidates
35   UTTAR PRADESH      332631
21     MAHARASHTRA      275245
30       RAJASTHAN      193130
32      TAMIL NADU      153704
16       KARNATAKA      150897
17          KERALA      138546
4            BIHAR      136193
20  MADHYA PRADESH      130238
37     WEST BENGAL      117323
11         GUJARAT       86952

In [ ]:
# 🟢 Q17 — Above Average Students
# Har state ke average Marks se zyada Marks laane wale students find karo.
# Output mein ye columns hone chahiye:
# state, Marks, city, center_name
#
# Hint:
# Q12 mein banaya hua State_Avg_Marks column use kar.
# loc() se un students ko filter kar jinke Marks,
# State_Avg_Marks se greater hain.

df_17 = df.loc[df['Marks'] > df['State_Avg_Marks']]
# Sirf un students ko filter kiya jinke Marks state average se zyada hain

print(df_17[['state', 'Marks', 'city', 'center_name']])
# Required columns ka output dikhaya

                                    state  Marks        city  \
1        ANDAMAN AND NICOBAR ISLANDS (UT)    226  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)    449  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)    424  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)    222  PORT BLAIR
10       ANDAMAN AND NICOBAR ISLANDS (UT)    322  PORT BLAIR
...                                   ...    ...         ...
2333143                       WEST BENGAL    415     KALYANI
2333148                       WEST BENGAL    592     KALYANI
2333150                       WEST BENGAL    233     KALYANI
2333153                       WEST BENGAL    250     KALYANI
2333157                       WEST BENGAL    279     KALYANI

                      center_name
1        KENDRIYA VIDYALAYA NO. 1
2        KENDRIYA VIDYALAYA NO. 1
3        KENDRIYA VIDYALAYA NO. 1
4        KENDRIYA VIDYALAYA NO. 1
10       KENDRIYA VIDYALAYA NO. 1
...                           ...
2333143     CHAKDAHA MODEL SCHOOL
2333148     CHAKDAHA MODEL SCHOOL
2333150     CHAKDAHA MODEL SCHOOL
2333153     CHAKDAHA MODEL SCHOOL
2333157     CHAKDAHA MODEL SCHOOL

[905263 rows x 4 columns]

In [ ]:
# 🟢 Q18 — State-wise High Scorers Percentage

# NEET dataset df mein har state ke un candidates ka percentage calculate karo jinke Marks > 500 hain.

# Output columns:

# state

# High_Scorers

# Total_Candidates

# High_Scorer_Percentage

High_Scorers = df.loc[df['Marks'] > 500]
# 500 se zyada Marks wale candidates filter kiye

High_Scorers = High_Scorers.groupby('state').agg({'Marks': 'count'}).reset_index()
# Har state ke high scorers count kiye

High_Scorers = High_Scorers.rename(columns={'Marks': 'High_Scorers'})
# Marks column ka naam High_Scorers rakha

total_candidates = df.groupby('state').agg({'Marks': 'count'}).reset_index()
# Har state ke total candidates count kiye

total_candidates = total_candidates.rename(columns={'Marks': 'Total_Candidates'})
# Marks column ka naam Total_Candidates rakha

df_18 = High_Scorers.merge(total_candidates, on='state', how='inner')
# Dono tables ko state ke basis par merge kiya

df_18['High_Scorer_Percentage'] = (df_18['High_Scorers'] / df_18['Total_Candidates']) * 100
# Har state mein high scorers ka percentage nikala

print(df_18)
# Final output display kiya

                               state  High_Scorers  Total_Candidates  \
0   ANDAMAN AND NICOBAR ISLANDS (UT)            28              1025
1                     ANDHRA PRADESH          7860             63846
2                  ARUNACHAL PRADESH            96              4774
3                              ASSAM          2865             44273
4                              BIHAR          9487            136193
5                     CHANDIGARH(UT)           632              3530
6                       CHHATTISGARH          2061             44241
7        DADRA AND NAGAR HAVELI (UT)            72              1207
8                 DAMAN AND DIU (UT)            14               769
9                              DELHI          7791             66090
10                               GOA           279              4930
11                           GUJARAT          9383             86952
12                           HARYANA          7510             54864
13                  HIMACHAL PRADESH          1412             19064
14                 JAMMU AND KASHMIR          2942             47553
15                         JHARKHAND          2720             34404
16                         KARNATAKA         13091            150897
17                            KERALA         14978            138546
18                        LADAKH(UT)             2               715
19                  LAKSHADWEEP (UT)             4               167
20                    MADHYA PRADESH          6062            130238
21                       MAHARASHTRA         21108            275245
22                           MANIPUR           425              8946
23                         MEGHALAYA            50              3757
24                           MIZORAM             5              2569
25                          NAGALAND            25              3705
26                            ODISHA          5666             64318
27                     OUTSIDE-INDIA           360              4750
28                    PUDUCHERRY(UT)           371              5810
29                            PUNJAB          2497             26573
30                         RAJASTHAN         33090            193130
31                            SIKKIM            33              1444
32                        TAMIL NADU         14251            153704
33                         TELANGANA          4507             77892
34                           TRIPURA           247              5098
35                     UTTAR PRADESH         23341            332631
36                       UTTARAKHAND          1725             21989
37                       WEST BENGAL         11601            117323

    High_Scorer_Percentage
0                 2.731707
1                12.310873
2                 2.010892
3                 6.471213
4                 6.965850
5                17.903683
6                 4.658575
7                 5.965203
8                 1.820546
9                11.788470
10                5.659229
11               10.791011
12               13.688393
13                7.406630
14                6.186781
15                7.906057
16                8.675454
17               10.810850
18                0.279720
19                2.395210
20                4.654556
21                7.668804
22                4.750727
23                1.330849
24                0.194628
25                0.674764
26                8.809354
27                7.578947
28                6.385542
29                9.396756
30               17.133537
31                2.285319
32                9.271717
33                5.786217
34                4.845037
35                7.017085
36                7.844832
37                9.888087

In [ ]:
# 🟢 Q19 — State-wise Marks Category

# NEET dataset df mein har state ke andar:

# High students ka count

# Medium students ka count

# Low students ka count

# nikalna hai.

# Condition: Q10 mein banaya hua High_Medium_Low column use karna.

# Hint: groupby() mein state aur High_Medium_Low dono use honge, phir agg() se count nikalna hai.

# Chal brother, pehla attempt bhej! 💪

df['High_Medium_Low'] = np.where(df['Marks'] > 500, 'High', np.where(df['Marks'] >= 300, 'Medium','Low'))

df_19 = df.groupby(['state','High_Medium_Low'] ).agg({'Marks' : 'count'})

print(df_19)

                                                  Marks
state                            High_Medium_Low
ANDAMAN AND NICOBAR ISLANDS (UT) High                28
                                 Low                831
                                 Medium             166
ANDHRA PRADESH                   High              7860
                                 Low              39368
...                                                 ...
UTTARAKHAND                      Low              16366
                                 Medium            3898
WEST BENGAL                      High             11601
                                 Low              85609
                                 Medium           20113

[114 rows x 1 columns]

In [ ]:
# 🟢 Q20 — State-wise Top Scorer Details

# NEET dataset df mein har state ke top 3 highest-scoring candidates find karo.

# Output mein ye columns hone chahiye:

# state

# Marks

# city

df_20 = df.sort_values(by= 'Marks' ,ascending=False)

df_20 = df.groupby('state').head(3)

print(df_20)

                                    state               city  \
0        ANDAMAN AND NICOBAR ISLANDS (UT)         PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)         PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)         PORT BLAIR
1025                       ANDHRA PRADESH             GUNTUR
1026                       ANDHRA PRADESH             GUNTUR
...                                   ...                ...
2193851                       UTTARAKHAND           DEHRADUN
2193852                       UTTARAKHAND           DEHRADUN
2215839                       WEST BENGAL  NORTH 24 PARGANAS
2215840                       WEST BENGAL  NORTH 24 PARGANAS
2215841                       WEST BENGAL  NORTH 24 PARGANAS

                                           center_name  center_num  Srlno.  \
0                             KENDRIYA VIDYALAYA NO. 1      110101       1
1                             KENDRIYA VIDYALAYA NO. 1      110101       2
2                             KENDRIYA VIDYALAYA NO. 1      110101       3
1025               LITTLE FLOWER ENGLISH MEDIUM SCHOOL      120101       1
1026               LITTLE FLOWER ENGLISH MEDIUM SCHOOL      120101       2
...                                                ...         ...     ...
2193851  NIRMAL ASHRAM DEEPMALA P PUB SCH RISHIKESH UK      450101       2
2193852  NIRMAL ASHRAM DEEPMALA P PUB SCH RISHIKESH UK      450101       3
2215839                              ADAMAS UNIVERSITY      460101       1
2215840                              ADAMAS UNIVERSITY      460101       2
2215841                              ADAMAS UNIVERSITY      460101       3

         Marks High_Medium_Low  State_Avg_Marks    Performance
0           46             Low       192.737561  Below_Average
1          226             Low       192.737561  Above_Average
2          449          Medium       192.737561  Above_Average
1025       163             Low       260.971024  Below_Average
1026       354          Medium       260.971024  Above_Average
...        ...             ...              ...            ...
2193851     50             Low       216.313793  Below_Average
2193852     26             Low       216.313793  Below_Average
2215839    186             Low       219.478585  Below_Average
2215840    129             Low       219.478585  Below_Average
2215841    235             Low       219.478585  Above_Average

[114 rows x 9 columns]

In [ ]:
# 🟢 Q21 — State-wise Top Scorer
# NEET dataset df mein har state ka highest-scoring candidate find karo.
# Output columns:
# - state
# - Marks
# - city
# - center_name

df_21 = df.groupby(' state').agg({'Marks': 'max'}).reset_index()
# Har state ke highest Marks nikale aur state ko normal column banaya

df_21 = df.merge(df_21, on=' state', how='inner')
# State ke basis par maximum Marks ko original data ke saath merge kiya

df_21 = df_21.loc[df_21['Marks_x'] == df_21['Marks_y']]
# Sirf un candidates ko rakha jinke Marks state ke maximum Marks ke equal hain

print(df_21[[' state', 'Marks_x', 'city', 'center_name']])
# State, highest Marks, city aur centre ka output dikhaya

                                    state  Marks_x         city  \
55       ANDAMAN AND NICOBAR ISLANDS (UT)      680   PORT BLAIR
12528                      ANDHRA PRADESH      720      NELLORE
18809                      ANDHRA PRADESH      720   VIJAYAWADA
19979                      ANDHRA PRADESH      720   VIJAYAWADA
21180                      ANDHRA PRADESH      720   VIJAYAWADA
...                                   ...      ...          ...
2153326                     UTTAR PRADESH      720      LUCKNOW
2201862                       UTTARAKHAND      720     HALDWANI
2260412                       WEST BENGAL      720      KOLKATA
2279145                       WEST BENGAL      720  MURSHIDABAD
2314725                       WEST BENGAL      720     SILIGURI

                                               center_name
55                                KENDRIYA VIDYALAYA NO. 1
12528           PADMAVATHI VIDYALAYA SULLURPETA NELLORE AP
18809    POTTI SRIRAMULU CHALAVADI MALLIKARJUNA RAO COL...
19979                    KAKARAPARTI BHAVANARAYANA COLLEGE
21180      DHANEKULA INSTITUTE OF ENGINEERING & TECHNOLOGY
...                                                    ...
2153326                             S.D.S.N. MAHAVIDYALAYA
2201862               SRI GURU TEG BAHADUR SR. SEC. SCHOOL
2260412            RCC INSTITUTE OF INFORMATION TECHNOLOGY
2279145                                GUIDANCE FOUNDATION
2314725                                       D.A.V SCHOOL

[109 rows x 4 columns]

In [ ]:
# 🟢 Q22 — State-wise Lowest Scorer
# NEET dataset df mein har state ka lowest-scoring candidate find karo.
#
# Output columns:
# state, Marks, city, center_name
#
# Rule:
# Har state se sirf lowest Marks wale candidate ki row nikalni hai.
# Agar multiple candidates ke lowest Marks same hain, toh sabko include karna.
#
# Hint:
# Q21 ka pattern use kar, bas maximum ki jagah minimum Marks nikalne hain.

df_22 = df.groupby(' state').agg({'Marks': 'min'}).reset_index()
# Har state ke minimum Marks nikale aur state ko normal column banaya

df_22 = df.merge(df_22, on=' state', how='inner')
# Minimum Marks ko original data ke saath merge kiya

df_22 = df_22.loc[df_22['Marks_x'] == df_22['Marks_y']]
# Sirf lowest Marks wale candidates ko filter kiya

print(df_22[[' state', 'Marks_x', 'city', 'center_name']])
# State, lowest Marks, city aur centre display kiya

                                    state  Marks_x                   city  \
140      ANDAMAN AND NICOBAR ISLANDS (UT)       -5             PORT BLAIR
42676                      ANDHRA PRADESH      -89          VISAKHAPATNAM
67935                   ARUNACHAL PRADESH      -16    ITANAGAR/NAHARLAGUN
85323                               ASSAM     -102                 NAGAON
212320                              BIHAR     -180                  PATNA
232819                              BIHAR     -180                KATIHAR
251919                     CHANDIGARH(UT)        0      CHANDIGARH/MOHALI
277134                       CHHATTISGARH      -44                 RAIPUR
289350                       CHHATTISGARH      -44                 KANKER
298859        DADRA AND NAGAR HAVELI (UT)      -10               SILVASSA
299516                 DAMAN AND DIU (UT)       -4                  DAMAN
348209                              DELHI      -36        DELHI/NEW DELHI
368295                                GOA      -35  PANAJI/MADGAON/MARGAO
427481                            GUJARAT     -149                  SURAT
463314                            HARYANA      -96              FARIDABAD
526815                   HIMACHAL PRADESH      -49                  KULLU
547306                  JAMMU AND KASHMIR      -56              BARAMULLA
583255                          JHARKHAND      -50                  DUMKA
680046                          KARNATAKA      -87    SHIVAMOGA (SHIMOGA)
819211                             KERALA     -136     THIRUVANANTHAPURAM
903513                         LADAKH(UT)      -15                 KARGIL
904036                   LAKSHADWEEP (UT)       -8              KAVARATTI
979117                     MADHYA PRADESH      -53               JABALPUR
1177454                       MAHARASHTRA     -170               BULDHANA
1314301                           MANIPUR      -48                 IMPHAL
1321672                         MEGHALAYA      -15                   TURA
1324288                           MIZORAM      -12                 AIZAWL
1325527                          NAGALAND      -19                DIMAPUR
1361379                            ODISHA      -65            BHUBANESWAR
1397289                     OUTSIDE-INDIA       -5                SHARJAH
1401131                    PUDUCHERRY(UT)      -24             PUDUCHERRY
1415669                            PUNJAB     -144               LUDHIANA
1528613                         RAJASTHAN     -135                 JAIPUR
1623291                            SIKKIM     -103                GANGTOK
1671301                        TAMIL NADU      -38                CHENNAI
1747816                        TAMIL NADU      -38                VELLORE
1756488                        TAMIL NADU      -38               DINDIGUL
1800174                         TELANGANA     -126             KARIMNAGAR
1860629                           TRIPURA      -35               AGARTALA
2036775                     UTTAR PRADESH      -67               VARANASI
2205377                       UTTARAKHAND      -55               HALDWANI
2281730                       WEST BENGAL     -135            MURSHIDABAD

                                               center_name
140                               KENDRIYA VIDYALAYA NO. 1
42676         SANKETIKA VIDYA PARISHAD ENGINEERING COLLEGE
67935                                KINGCUP PUBLIC SCHOOL
85323    SANDIPANI VIDYA MANDIR SR. SECONDARY SCHOOL (C...
212320        SATYAM INTERNATIONAL INSTITUTE OF TECHNOLOGY
232819                      SCOTTISH PUBLIC SCHOOL KATIHAR
251919               POST GRADUATE GOVT. COLLEGE FOR GIRLS
277134                            DAFFODILS ENGLISH SCHOOL
289350              ST. MICHAEL''S HIGHER SECONDARY SCHOOL
298859                                    ADAVAITA GURUKUL
299516                           COAST GUARD PUBLIC SCHOOL
348209                            VIVEKANAND PUBLIC SCHOOL
368295                                  THE KING''S SCHOOL
427481                J B DIAMONDS &KARP IMPEXVIDYA SANKUL
463314     K L M DAYANAND HIGH SCHOOL SEC-17 FARIDABAD HRY
526815                                LA MONTESSORI SCHOOL
547306                   GULZAR MEMORIAL EDUCATIONAL TRUST
583255                           SACRED HEART SCHOOL DUMKA
680046                      ST. JOSEPHS SCHOOL BHADRAVATHI
819211                            ST.THOMAS CENTRAL SCHOOL
903513                           GOVERNMENT DEGREE COLLEGE
904036                       PM SHRI.GSS SCHOOL, KAVARATTI
979117               RYAN INTERNATIONAL SCHOOL JABALPUR MP
1177454             SAHAKAR VIDHYA MANDIR & JUNIOR COLLEGE
1314301                        REGULAR ENGLISH HIGH SCHOOL
1321672            GOVERNMENT BOYS HIGHER SECONDARY SCHOOL
1324288                           MODERN ENGLISH HS SCHOOL
1325527                                       HOPE ACADEMY
1361379                                   GITA BHUBANESWAR
1397289                              SHARJAH INDIAN SCHOOL
1401131                        ACHARIYA BALA SIKSHA MANDIR
1415669                            B C M ARYA MODEL SCHOOL
1528613                               TAGORE PUBLIC SCHOOL
1623291                      GOVT GIRLS SR SECONDRY SCHOOL
1671301  SMT NARBADA DEVI J AGARWAL VIVEKANANDA VIDYALA...
1747816                SHRISHTI VIDYASHRAM SR. SEC. SCHOOL
1756488         PSNA COLLEGE OF ENGINEERING AND TECHNOLOGY
1800174                     VIVEKANANDA RESIDENTIAL SCHOOL
1860629                      HINDI HIGHER SECONDARY SCHOOL
2036775                SETH M. R. JAIPURIA SCHOOLS BANARAS
2205377          UNIVERSAL CONVENT SENIOR SECONDARY SCHOOL
2281730                             BARWAN N.S HIGH SCHOOL

In [14]:
# 🟢 Q23 — State-wise Median
# NEET dataset df mein har state ke candidates ke median Marks find karo.
# Output columns:
# - state
# - Median_Marks

# 🟢 Q23 — State-wise Median

df_23 = df.groupby(' state').agg({'Marks': 'median'}).reset_index()
# Har state ke median Marks nikale aur state ko normal column banaya

df_23 = df_23.rename(columns={'Marks': 'Median_Marks'})
# Marks column ka naam Median_Marks rakha

print(df_23[[' state', 'Median_Marks']])
# State aur uske median Marks display kiye

                               state  Median_Marks
0   ANDAMAN AND NICOBAR ISLANDS (UT)         155.0
1                     ANDHRA PRADESH         224.0
2                  ARUNACHAL PRADESH         129.0
3                              ASSAM         137.0
4                              BIHAR         133.0
5                     CHANDIGARH(UT)         270.0
6                       CHHATTISGARH         137.0
7        DADRA AND NAGAR HAVELI (UT)         183.0
8                 DAMAN AND DIU (UT)         150.0
9                              DELHI         213.0
10                               GOA         152.0
11                           GUJARAT         197.0
12                           HARYANA         215.0
13                  HIMACHAL PRADESH         183.0
14                 JAMMU AND KASHMIR         162.0
15                         JHARKHAND         157.0
16                         KARNATAKA         166.0
17                            KERALA         181.0
18                        LADAKH(UT)         137.0
19                  LAKSHADWEEP (UT)         115.0
20                    MADHYA PRADESH         121.0
21                       MAHARASHTRA         148.0
22                           MANIPUR         157.0
23                         MEGHALAYA         125.0
24                           MIZORAM         126.0
25                          NAGALAND         144.0
26                            ODISHA         146.0
27                     OUTSIDE-INDIA         221.0
28                    PUDUCHERRY(UT)         140.0
29                            PUNJAB         179.0
30                         RAJASTHAN         236.0
31                            SIKKIM         144.0
32                        TAMIL NADU         160.0
33                         TELANGANA         183.0
34                           TRIPURA         132.0
35                     UTTAR PRADESH         137.0
36                       UTTARAKHAND         168.0
37                       WEST BENGAL         163.0

In [ ]:
# 🟢 Q24 — State-wise Marks Variation
# NEET dataset df mein har state ke Marks ka standard deviation calculate karo.
# Output columns:
# - state
# - Marks_Std

df_24 = df.groupby(' state').agg({'Marks': 'std'}).reset_index()
# Har state ke Marks ka standard deviation nikala

df_24 = df_24.rename(columns={'Marks' : 'Marks_Std'})
# Marks column ka naam Marks_Std rakha

print(df_24[[' state', 'Marks_Std']])
# State aur uska standard deviation display kiya

                                    state  Marks_Std
0        ANDAMAN AND NICOBAR ISLANDS (UT)         46
1        ANDAMAN AND NICOBAR ISLANDS (UT)        226
2        ANDAMAN AND NICOBAR ISLANDS (UT)        449
3        ANDAMAN AND NICOBAR ISLANDS (UT)        424
4        ANDAMAN AND NICOBAR ISLANDS (UT)        222
...                                   ...        ...
2333157                       WEST BENGAL        279
2333158                       WEST BENGAL        102
2333159                       WEST BENGAL         14
2333160                       WEST BENGAL        179
2333161                       WEST BENGAL         91

[2333162 rows x 2 columns]

In [18]:
# Bhai 🔥 Q25 — State-wise Marks Range
# Task: Har state ke highest aur lowest Marks ka difference nikaalna hai.
# - df use karna hai.
# - Har state ke maximum aur minimum Marks nikalo.
# - Ek naya column Marks_Range banao: Maximum Marks - Minimum Marks.
# - Final output mein sirf state, Max_Marks, Min_Marks, Marks_Range dikhana.

df_25 = df.groupby(' state').agg({'Marks': ['min', 'max']}).reset_index()
# Har state ke minimum aur maximum Marks nikale

df_25.columns = ['state', 'Min_Marks', 'Max_Marks']
# Columns ke naam simple kiye

df_25['Marks_Range'] = df_25['Max_Marks'] - df_25['Min_Marks']
# Maximum aur minimum Marks ka difference nikala

print(df_25[['state', 'Max_Marks', 'Min_Marks', 'Marks_Range']])
# Required columns ka final output dikhaya

                               state  Max_Marks  Min_Marks  Marks_Range
0   ANDAMAN AND NICOBAR ISLANDS (UT)        680         -5          685
1                     ANDHRA PRADESH        720        -89          809
2                  ARUNACHAL PRADESH        705        -16          721
3                              ASSAM        715       -102          817
4                              BIHAR        720       -180          900
5                     CHANDIGARH(UT)        715          0          715
6                       CHHATTISGARH        711        -44          755
7        DADRA AND NAGAR HAVELI (UT)        692        -10          702
8                 DAMAN AND DIU (UT)        665         -4          669
9                              DELHI        720        -36          756
10                               GOA        697        -35          732
11                           GUJARAT        720       -149          869
12                           HARYANA        716        -96          812
13                  HIMACHAL PRADESH        711        -49          760
14                 JAMMU AND KASHMIR        715        -56          771
15                         JHARKHAND        720        -50          770
16                         KARNATAKA        720        -87          807
17                            KERALA        720       -136          856
18                        LADAKH(UT)        533        -15          548
19                  LAKSHADWEEP (UT)        609         -8          617
20                    MADHYA PRADESH        715        -53          768
21                       MAHARASHTRA        720       -170          890
22                           MANIPUR        672        -48          720
23                         MEGHALAYA        692        -15          707
24                           MIZORAM        559        -12          571
25                          NAGALAND        648        -19          667
26                            ODISHA        715        -65          780
27                     OUTSIDE-INDIA        710         -5          715
28                    PUDUCHERRY(UT)        690        -24          714
29                            PUNJAB        720       -144          864
30                         RAJASTHAN        720       -135          855
31                            SIKKIM        656       -103          759
32                        TAMIL NADU        720        -38          758
33                         TELANGANA        715       -126          841
34                           TRIPURA        720        -35          755
35                     UTTAR PRADESH        720        -67          787
36                       UTTARAKHAND        720        -55          775
37                       WEST BENGAL        720       -135          855