In [ ]:
#import libraries 
import numpy as np 
import pandas as pd 

import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.metrics  import mean_absolute_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

In [ ]:
# Read  data 

df = pd.read_csv("demand_forecasting_dataset (1).csv")
df

,date,product_id,category_id,store_id,historical_sales,price,promotion_flag,holiday_flag,economic_index,target_demand
0,2022-01-02,1043,4,9,16,48.29,0,0,84.07,8
1,2022-01-02,1012,4,2,25,44.01,0,0,106.87,22
2,2022-01-03,1003,5,4,26,9.44,1,0,104.98,29
3,2022-01-03,1005,4,1,23,5.42,1,1,92.75,22
4,2022-01-04,1011,1,5,12,21.86,1,1,103.60,27
...,...,...,...,...,...,...,...,...,...,...
4916,2035-06-19,1018,5,7,25,35.46,1,0,102.21,32
4917,2035-06-19,1029,5,4,21,15.05,0,1,82.47,17
4918,2035-06-19,1019,5,10,24,43.68,0,1,99.41,19
4919,2035-06-19,1027,5,4,23,25.52,0,0,93.95,22
4920,2035-06-22,1046,2,6,23,22.14,1,1,92.98,26

In [ ]:
# Top rows ko dekh raha hu 

df.head(5)

,date,product_id,category_id,store_id,historical_sales,price,promotion_flag,holiday_flag,economic_index,target_demand
0,2022-01-02,1043,4,9,16,48.29,0,0,84.07,8
1,2022-01-02,1012,4,2,25,44.01,0,0,106.87,22
2,2022-01-03,1003,5,4,26,9.44,1,0,104.98,29
3,2022-01-03,1005,4,1,23,5.42,1,1,92.75,22
4,2022-01-04,1011,1,5,12,21.86,1,1,103.60,27

In [ ]:
# Last rows  ko dekh raha hu  

df.tail(5)

,date,product_id,category_id,store_id,historical_sales,price,promotion_flag,holiday_flag,economic_index,target_demand
4916,2035-06-19,1018,5,7,25,35.46,1,0,102.21,32
4917,2035-06-19,1029,5,4,21,15.05,0,1,82.47,17
4918,2035-06-19,1019,5,10,24,43.68,0,1,99.41,19
4919,2035-06-19,1027,5,4,23,25.52,0,0,93.95,22
4920,2035-06-22,1046,2,6,23,22.14,1,1,92.98,26

In [ ]:
# Random Rows 

df.sample(10)

,date,product_id,category_id,store_id,historical_sales,price,promotion_flag,holiday_flag,economic_index,target_demand
3966,2032-10-18,1039,3,8,16,16.88,1,0,106.84,23
795,2024-05-01,1026,2,8,19,30.84,1,0,119.43,24
4664,2034-10-13,1010,2,9,17,32.74,1,0,108.96,31
2941,2030-02-12,1045,5,4,26,16.84,0,0,99.28,28
2455,2028-11-10,1046,3,7,14,8.90,0,0,109.03,15
45,2022-02-16,1032,5,7,18,29.76,1,1,103.91,24
1228,2025-06-18,1033,2,2,18,24.47,0,1,101.96,22
240,2022-09-07,1011,2,7,25,49.52,0,0,91.59,26
4375,2033-12-13,1049,5,4,19,9.42,0,1,104.14,15
2612,2029-04-13,1034,5,8,19,23.05,1,0,109.98,30

In [ ]:
# Shape

df.shape

(4921, 10)

In [ ]:
# Colums ko dekh raha tha 

df.columns

Index(['date', 'product_id', 'category_id', 'store_id', 'historical_sales',
       'price', 'promotion_flag', 'holiday_flag', 'economic_index',
       'target_demand'],
      dtype='str')

In [ ]:
# data types 

df.dtypes

date                    str
product_id            int64
category_id           int64
store_id              int64
historical_sales      int64
price               float64
promotion_flag        int64
holiday_flag          int64
economic_index      float64
target_demand         int64
dtype: object

In [ ]:
# DAta ka information dekh raha tha 

df.info

<bound method DataFrame.info of             date  product_id  category_id  store_id  historical_sales  price  \
0     2022-01-02        1043            4         9                16  48.29
1     2022-01-02        1012            4         2                25  44.01
2     2022-01-03        1003            5         4                26   9.44
3     2022-01-03        1005            4         1                23   5.42
4     2022-01-04        1011            1         5                12  21.86
...          ...         ...          ...       ...               ...    ...
4916  2035-06-19        1018            5         7                25  35.46
4917  2035-06-19        1029            5         4                21  15.05
4918  2035-06-19        1019            5        10                24  43.68
4919  2035-06-19        1027            5         4                23  25.52
4920  2035-06-22        1046            2         6                23  22.14

      promotion_flag  holiday_flag  economic_index  target_demand
0                  0             0           84.07              8
1                  0             0          106.87             22
2                  1             0          104.98             29
3                  1             1           92.75             22
4                  1             1          103.60             27
...              ...           ...             ...            ...
4916               1             0          102.21             32
4917               0             1           82.47             17
4918               0             1           99.41             19
4919               0             0           93.95             22
4920               1             1           92.98             26

[4921 rows x 10 columns]>

In [17]:
# Statistical Summary 

df.describe

<bound method NDFrame.describe of             date  product_id  category_id  store_id  historical_sales  price  \
0     2022-01-02        1043            4         9                16  48.29
1     2022-01-02        1012            4         2                25  44.01
2     2022-01-03        1003            5         4                26   9.44
3     2022-01-03        1005            4         1                23   5.42
4     2022-01-04        1011            1         5                12  21.86
...          ...         ...          ...       ...               ...    ...
4916  2035-06-19        1018            5         7                25  35.46
4917  2035-06-19        1029            5         4                21  15.05
4918  2035-06-19        1019            5        10                24  43.68
4919  2035-06-19        1027            5         4                23  25.52
4920  2035-06-22        1046            2         6                23  22.14

      promotion_flag  holiday_flag  economic_index  target_demand
0                  0             0           84.07              8
1                  0             0          106.87             22
2                  1             0          104.98             29
3                  1             1           92.75             22
4                  1             1          103.60             27
...              ...           ...             ...            ...
4916               1             0          102.21             32
4917               0             1           82.47             17
4918               0             1           99.41             19
4919               0             0           93.95             22
4920               1             1           92.98             26

[4921 rows x 10 columns]>

In [18]:
#11 Missing  Values  find kr raha tha 

df.isnull().sum()

date                0
product_id          0
category_id         0
store_id            0
historical_sales    0
price               0
promotion_flag      0
holiday_flag        0
economic_index      0
target_demand       0
dtype: int64

In [19]:
#12. Duplicate Rows 

df.duplicated().sum()

np.int64(0)

In [ ]:
#13. Remove Duplikcate 

df= df.drop_duplicates