In [4]:
b = pd.DataFrame(a)

In [24]:
import pandas as pd

In [5]:
b

        person1 person2 person3
name      Rahul    Aman   Rohit
surname  Sharma   Verma   Patel
address  Bhilai  Raipur    Durg

In [14]:
b[ "person1"]

name        Rahul
surname    Sharma
address    Bhilai
Name: person1, dtype: str

In [18]:
import pandas as pd

data = {
    'Name': ['Virat', 'Rohit', 'KL'],
    'Surname': ['Kohli', 'Sharma', 'Rahul'],
    'Address': ['London', 'Mumbai', 'Mumbai'],
    'IPL_team': ['RCB', 'MI', 'DC']
}

df = pd.DataFrame(data)

print(df)

    Name Surname Address IPL_team
0  Virat   Kohli  London      RCB
1  Rohit  Sharma  Mumbai       MI
2     KL   Rahul  Mumbai       DC

In [19]:
data = {
    'Name': ['KL', 'Rohit', 'Virat'],
    'Surname': ['Rahul', 'Sharma', 'Kohli'],
    'Address': ['Mumbai', 'Mumbai', 'London'],
    'IPL_team': ['DC', 'MI', 'RCB']
}

In [20]:
df['Name'].str.upper()

0    VIRAT
1    ROHIT
2       KL
Name: Name, dtype: str

In [21]:
df['Name'].str.lower()

0    virat
1    rohit
2       kl
Name: Name, dtype: str

In [23]:
df['Runs'] = [5000,3000,20000]
print(df)

    Name Surname Address IPL_team   Runs
0  Virat   Kohli  London      RCB   5000
1  Rohit  Sharma  Mumbai       MI   3000
2     KL   Rahul  Mumbai       DC  20000

In [25]:
df['Runs']

0     5000
1     3000
2    20000
Name: Runs, dtype: int64

In [27]:
df.describe()

               Runs
count      3.000000
mean    9333.333333
std     9291.573243
min     3000.000000
25%     4000.000000
50%     5000.000000
75%    12500.000000
max    20000.000000

In [28]:
df['number_of_centuries'] = [30,20,5]
print(df)

    Name Surname Address IPL_team   Runs  number_of_centuries
0  Virat   Kohli  London      RCB   5000                   30
1  Rohit  Sharma  Mumbai       MI   3000                   20
2     KL   Rahul  Mumbai       DC  20000                    5

In [30]:
df.describe()

               Runs  number_of_centuries
count      3.000000             3.000000
mean    9333.333333            18.333333
std     9291.573243            12.583057
min     3000.000000             5.000000
25%     4000.000000            12.500000
50%     5000.000000            20.000000
75%    12500.000000            25.000000
max    20000.000000            30.000000

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 3 non-null      str
 1   Surname              3 non-null      str
 2   Address              3 non-null      str
 3   IPL_team             3 non-null      str
 4   Runs                 3 non-null      int64
 5   number_of_centuries  3 non-null      int64
dtypes: int64(2), str(4)
memory usage: 276.0 bytes

In [32]:
df.iloc[0:]

    Name Surname Address IPL_team   Runs  number_of_centuries
0  Virat   Kohli  London      RCB   5000                   30
1  Rohit  Sharma  Mumbai       MI   3000                   20
2     KL   Rahul  Mumbai       DC  20000                    5

In [33]:
df.iloc[1:]

    Name Surname Address IPL_team   Runs  number_of_centuries
1  Rohit  Sharma  Mumbai       MI   3000                   20
2     KL   Rahul  Mumbai       DC  20000                    5

In [34]:
df.iloc[0,0]

'Virat'

In [35]:
df.iloc[[0,1],]

    Name Surname Address IPL_team  Runs  number_of_centuries
0  Virat   Kohli  London      RCB  5000                   30
1  Rohit  Sharma  Mumbai       MI  3000                   20

In [37]:
df.iloc[[0,1],[0.1]]

    Name
0  Virat
1  Rohit