In [58]:
import pandas as pd

In [59]:
import pandas as pd

data = {
    'Name': ['Virat', 'Rohit', 'KL'],
    'Surname': ['Kohli', 'Sharma', 'Rahul'],
    'Address': ['London', 'Mumbai', 'Mumbai'],
    'IPL_team': ['RCB', 'MI', 'DC']
}

df = pd.DataFrame(data)

print(df)

    Name Surname Address IPL_team
0  Virat   Kohli  London      RCB
1  Rohit  Sharma  Mumbai       MI
2     KL   Rahul  Mumbai       DC

In [60]:
data = {
    'Name': ['KL', 'Rohit', 'Virat'],
    'Surname': ['Rahul', 'Sharma', 'Kohli'],
    'Address': ['Mumbai', 'Mumbai', 'London'],
    'IPL_team': ['DC', 'MI', 'RCB']
}

In [61]:
df['Name'].str.upper()

0    VIRAT
1    ROHIT
2       KL
Name: Name, dtype: str

In [62]:
df['Name'].str.lower()

0    virat
1    rohit
2       kl
Name: Name, dtype: str

In [63]:
df['Runs'] = [5000,3000,20000]
print(df)

    Name Surname Address IPL_team   Runs
0  Virat   Kohli  London      RCB   5000
1  Rohit  Sharma  Mumbai       MI   3000
2     KL   Rahul  Mumbai       DC  20000

In [64]:
df['Runs']

0     5000
1     3000
2    20000
Name: Runs, dtype: int64

In [65]:
df.describe()

               Runs
count      3.000000
mean    9333.333333
std     9291.573243
min     3000.000000
25%     4000.000000
50%     5000.000000
75%    12500.000000
max    20000.000000

In [66]:
df['number_of_centuries'] = [30,20,5]
print(df)

    Name Surname Address IPL_team   Runs  number_of_centuries
0  Virat   Kohli  London      RCB   5000                   30
1  Rohit  Sharma  Mumbai       MI   3000                   20
2     KL   Rahul  Mumbai       DC  20000                    5

In [67]:
df.describe()

               Runs  number_of_centuries
count      3.000000             3.000000
mean    9333.333333            18.333333
std     9291.573243            12.583057
min     3000.000000             5.000000
25%     4000.000000            12.500000
50%     5000.000000            20.000000
75%    12500.000000            25.000000
max    20000.000000            30.000000

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 3 non-null      str
 1   Surname              3 non-null      str
 2   Address              3 non-null      str
 3   IPL_team             3 non-null      str
 4   Runs                 3 non-null      int64
 5   number_of_centuries  3 non-null      int64
dtypes: int64(2), str(4)
memory usage: 276.0 bytes

In [ ]:
df.iloc[0:]  # isme i ka matlab hai index and loc ka maltab hai location

    Name Surname Address IPL_team   Runs  number_of_centuries
0  Virat   Kohli  London      RCB   5000                   30
1  Rohit  Sharma  Mumbai       MI   3000                   20
2     KL   Rahul  Mumbai       DC  20000                    5

In [70]:
df.iloc[1:]

    Name Surname Address IPL_team   Runs  number_of_centuries
1  Rohit  Sharma  Mumbai       MI   3000                   20
2     KL   Rahul  Mumbai       DC  20000                    5

In [71]:
df.iloc[0,0]

'Virat'

In [72]:
df.iloc[[0,1],]

    Name Surname Address IPL_team  Runs  number_of_centuries
0  Virat   Kohli  London      RCB  5000                   30
1  Rohit  Sharma  Mumbai       MI  3000                   20

In [73]:
df.iloc[[0,1],[0.1]]

    Name
0  Virat
1  Rohit

In [74]:
df.iloc[[1,2],[3,0,4]] #  pehele rows wala dkikhat ahia phir row ko slect kiya hai ahamne  parmeet yaad rakhna bro

  IPL_team   Name   Runs
1       MI  Rohit   3000
2       DC     KL  20000

In [75]:
df.loc[[0,1],["Name","Runs"]]

    Name  Runs
0  Virat  5000
1  Rohit  3000

In [76]:
df.loc[[2,1,0],["Address","IPL_team","Name"]]

  Address IPL_team   Name
2  Mumbai       DC     KL
1  Mumbai       MI  Rohit
0  London      RCB  Virat

In [77]:
df.set_index('Name')

      Surname Address IPL_team   Runs  number_of_centuries
Name
Virat   Kohli  London      RCB   5000                   30
Rohit  Sharma  Mumbai       MI   3000                   20
KL      Rahul  Mumbai       DC  20000                    5

In [78]:
df1 = df.set_index("Name")

In [83]:
df1.loc[['Virat',]]

      Surname Address IPL_team  Runs  number_of_centuries
Name
Virat   Kohli  London      RCB  5000                   30

In [84]:
df1.loc[["Virat","KL"],['Runs','IPL_team']]

        Runs IPL_team
Name
Virat   5000      RCB
KL     20000       DC

In [85]:
df.loc[df['Address']=='Mumbai',]

    Name Surname Address IPL_team   Runs  number_of_centuries
1  Rohit  Sharma  Mumbai       MI   3000                   20
2     KL   Rahul  Mumbai       DC  20000                    5

In [87]:
df.loc[df['Runs'] >= 1000,]

    Name Surname Address IPL_team   Runs  number_of_centuries
0  Virat   Kohli  London      RCB   5000                   30
1  Rohit  Sharma  Mumbai       MI   3000                   20
2     KL   Rahul  Mumbai       DC  20000                    5

In [88]:
df.loc[df['Runs'] > 1000, ['Name', 'Surname']]

    Name Surname
0  Virat   Kohli
1  Rohit  Sharma
2     KL   Rahul

In [89]:
df = pd.read_csv("Mall_Customers.csv")

In [1]:
singer = {"Name":['Paramcgwala','JordanSandhu','kayvee singh','shubh','dilgjitDosanjh'],
    'Number':["5245658574",'4875945678', '4875945645458','4875954678','6646545945678']



}