In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("all_neet_marks_2607.csv")

In [3]:
# 1. How many students are present in the dataset
df.shape[0]

2333162

In [25]:
df.describe()

         center_num        Srlno.         Marks
count  2.333162e+06  2.333162e+06  2.333162e+06
mean   3.224020e+05  2.902341e+02  2.171566e+02
std    1.049598e+05  2.171436e+02  1.662400e+02
min    1.101010e+05  1.000000e+00 -1.800000e+02
25%    2.602020e+05  1.240000e+02  8.700000e+01
50%    3.111190e+05  2.510000e+02  1.630000e+02
75%    4.122060e+05  4.080000e+02  3.130000e+02
max    9.914010e+05  1.968000e+03  7.200000e+02

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2333162 entries, 0 to 2333161
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   state        str
 1   city         str
 2   center_name  str
 3   center_num   int64
 4   Srlno.       int64
 5   Marks        int64
dtypes: int64(3), str(3)
memory usage: 106.8 MB

In [41]:
d = (df['Marks'] > 18) & (df['state'] == 'CHHATTISGARH')
print(d)

0          False
1          False
2          False
3          False
4          False
           ...
2333157    False
2333158    False
2333159    False
2333160    False
2333161    False
Length: 2333162, dtype: bool

In [4]:
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [5]:
# 2. How many states are present
df["state"].nunique()

38

In [21]:
df[['Marks','city']]

         Marks        city
0           46  PORT BLAIR
1          226  PORT BLAIR
2          449  PORT BLAIR
3          424  PORT BLAIR
4          222  PORT BLAIR
...        ...         ...
2333157    279     KALYANI
2333158    102     KALYANI
2333159     14     KALYANI
2333160    179     KALYANI
2333161     91     KALYANI

[2333162 rows x 2 columns]

In [6]:
sum(df['Marks'])

506661495

In [7]:
df['Marks'].sum()

np.int64(506661495)

In [8]:
df['Marks'].max()

np.int64(720)

In [9]:
df['Marks'].min()

np.int64(-180)

In [23]:
df.drop_duplicates()

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222
...,...,...,...,...,...,...
2333157,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,135,279
2333158,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,136,102
2333159,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,137,14
2333160,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,138,179
2333161,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,139,91

In [10]:
df["city"].nunique()  # tota number of uniwue value batata hai

567

In [11]:
df.groupby('state').agg({'Marks':'sum'})

                                     Marks
state
ANDAMAN AND NICOBAR ISLANDS (UT)    197556
ANDHRA PRADESH                    16661956
ARUNACHAL PRADESH                   777670
ASSAM                              8453395
BIHAR                             25683883
CHANDIGARH(UT)                     1076003
CHHATTISGARH                       8212726
DADRA AND NAGAR HAVELI (UT)         267872
DAMAN AND DIU (UT)                  138604
DELHI                             16928057
GOA                                 969592
GUJARAT                           21315275
HARYANA                           14338696
HIMACHAL PRADESH                   4302471
JAMMU AND KASHMIR                  9768028
JHARKHAND                          7153017
KARNATAKA                         33116704
KERALA                            32655149
LADAKH(UT)                          119037
LAKSHADWEEP (UT)                     25070
MADHYA PRADESH                    22695925
MAHARASHTRA                       55676862
MANIPUR                            1790773
MEGHALAYA                           587630
MIZORAM                             398553
NAGALAND                            640197
ODISHA                            13161367
OUTSIDE-INDIA                      1191185
PUDUCHERRY(UT)                     1140100
PUNJAB                             6076245
RAJASTHAN                         54144868
SIKKIM                              258971
TAMIL NADU                        33868938
TELANGANA                         17351045
TRIPURA                             908338
UTTAR PRADESH                     64103327
UTTARAKHAND                        4756524
WEST BENGAL                       25749886

In [12]:
df.groupby('state').agg({'Marks':'mean'})

                                       Marks
state
ANDAMAN AND NICOBAR ISLANDS (UT)  192.737561
ANDHRA PRADESH                    260.971024
ARUNACHAL PRADESH                 162.896942
ASSAM                             190.937931
BIHAR                             188.584457
CHANDIGARH(UT)                    304.816714
CHHATTISGARH                      185.636084
DADRA AND NAGAR HAVELI (UT)       221.932063
DAMAN AND DIU (UT)                180.239272
DELHI                             256.136435
GOA                               196.671805
GUJARAT                           245.138410
HARYANA                           261.349810
HIMACHAL PRADESH                  225.685638
JAMMU AND KASHMIR                 205.413497
JHARKHAND                         207.912365
KARNATAKA                         219.465622
KERALA                            235.698966
LADAKH(UT)                        166.485315
LAKSHADWEEP (UT)                  150.119760
MADHYA PRADESH                    174.264999
MAHARASHTRA                       202.281102
MANIPUR                           200.175833
MEGHALAYA                         156.409369
MIZORAM                           155.139354
NAGALAND                          172.792713
ODISHA                            204.629606
OUTSIDE-INDIA                     250.775789
PUDUCHERRY(UT)                    196.230637
PUNJAB                            228.662364
RAJASTHAN                         280.354518
SIKKIM                            179.342798
TAMIL NADU                        220.351702
TELANGANA                         222.757729
TRIPURA                           178.175363
UTTAR PRADESH                     192.716034
UTTARAKHAND                       216.313793
WEST BENGAL                       219.478585

In [13]:
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [14]:
df.groupby(['state','city','center_num']).agg({'Marks':['mean','count']}) # har city ka har state  ka marks ka mean and count nikale hai ya average marks

                                                             Marks
                                                              mean count
state                            city       center_num
ANDAMAN AND NICOBAR ISLANDS (UT) PORT BLAIR 110101      192.112798   461
                                            110102      192.594360   461
                                            110103      196.174757   103
ANDHRA PRADESH                   ANANTAPUR  121201      193.769316   906
                                            121202      207.425676   592
...                                                            ...   ...
WEST BENGAL                      SURI       461901      220.714660   764
                                            461902      225.723011   704
                                            461903      149.867012   579
                                            461904      151.131148   427
                                            461905      162.487437   199

[4750 rows x 2 columns]

In [15]:
df.groupby(['city','center_num']).agg({'Marks':['mean','count']})

                           Marks
                            mean count
city      center_num
ABU DHABI 990301      259.312608   579
ADILABAD  420901      190.109005   633
          420902      202.130350   514
          420903      175.142633   638
AGARTALA  430101      196.590508   906
...                          ...   ...
YAVATMAL  313407      171.421429   280
          313408      190.897436   234
          313409      171.177033   209
          313410      190.769953   213
          313411      165.135922   206

[4750 rows x 2 columns]

In [16]:
df.groupby(['city','center_num']).agg({'center_num':['count'],'Marks':['max','min','mean']}).reset_index()

           city center_num       Marks
                           count   max min        mean
0     ABU DHABI     990301   579   710   5  259.312608
1      ADILABAD     420901   633   617 -19  190.109005
2      ADILABAD     420902   514   624 -27  202.130350
3      ADILABAD     420903   638   642  -8  175.142633
4      AGARTALA     430101   906   720 -26  196.590508
...         ...        ...   ...   ...  ..         ...
4745   YAVATMAL     313407   280   670 -16  171.421429
4746   YAVATMAL     313408   234   664  -6  190.897436
4747   YAVATMAL     313409   209   623  -1  171.177033
4748   YAVATMAL     313410   213   608 -30  190.769953
4749   YAVATMAL     313411   206   617 -13  165.135922

[4750 rows x 6 columns]

In [17]:
df.groupby(['state','city']).agg({'Marks':['max'],'center_num':['nunique']})

                                                   Marks center_num
                                                     max    nunique
state                            city
ANDAMAN AND NICOBAR ISLANDS (UT) PORT BLAIR          680          3
ANDHRA PRADESH                   ANANTAPUR           653          4
                                 BHIMAVARAM          682          1
                                 CHIRALA             667          1
                                 CHITTOOR            656          3
...                                                  ...        ...
WEST BENGAL                      NORTH 24 PARGANAS   715         12
                                 PURBA MEDINIPUR     711          7
                                 SILIGURI            720         10
                                 SOUTH 24 PARGANAS   705         13
                                 SURI                695          5

[567 rows x 2 columns]

In [18]:
df.log[df.groupby(['state']).agg({'Marks':[max]})]

AttributeError: 'DataFrame' object has no attribute 'log'

In [ ]:
c = df.loc[df['Marks']<0,]
print(c.groupby('state').agg({'center_num':'count'})).sort_values(by='center_num',ascending= False).head(2)

               center_num
state
UTTAR PRADESH        1902
MAHARASHTRA          1785

In [ ]:
c = df.loc[(df['Marks']>=400) & (df['Marks']<=700),]
print(c.groupby('state').agg({'center_num':'count'}).sort_values(by='center_num',ascending= False))

                                  center_num
state
RAJASTHAN                              52699
UTTAR PRADESH                          42775
MAHARASHTRA                            39575
TAMIL NADU                             26674
KERALA                                 25172
KARNATAKA                              24553
WEST BENGAL                            20179
GUJARAT                                16926
BIHAR                                  16813
ANDHRA PRADESH                         15381
DELHI                                  13603
MADHYA PRADESH                         12831
TELANGANA                              12450
HARYANA                                12331
ODISHA                                  9585
JAMMU AND KASHMIR                       6090
ASSAM                                   5494
JHARKHAND                               4940
CHHATTISGARH                            4665
PUNJAB                                  4388
UTTARAKHAND                             3236
HIMACHAL PRADESH                        3017
MANIPUR                                 1112
CHANDIGARH(UT)                          1040
PUDUCHERRY(UT)                           768
OUTSIDE-INDIA                            725
GOA                                      537
TRIPURA                                  494
ARUNACHAL PRADESH                        257
DADRA AND NAGAR HAVELI (UT)              171
MEGHALAYA                                152
NAGALAND                                 135
SIKKIM                                   108
ANDAMAN AND NICOBAR ISLANDS (UT)          86
MIZORAM                                   65
DAMAN AND DIU (UT)                        48
LADAKH(UT)                                38
LAKSHADWEEP (UT)                          12

In [ ]:
c = df.loc[(df['Marks']>=400) | (df['Marks']<=700),]
print(c.groupby('state').agg({'center_num':'count'}).sort_values(by='center_num',ascending= False))

                                  center_num
state
UTTAR PRADESH                         332631
MAHARASHTRA                           275245
RAJASTHAN                             193130
TAMIL NADU                            153704
KARNATAKA                             150897
KERALA                                138546
BIHAR                                 136193
MADHYA PRADESH                        130238
WEST BENGAL                           117323
GUJARAT                                86952
TELANGANA                              77892
DELHI                                  66090
ODISHA                                 64318
ANDHRA PRADESH                         63846
HARYANA                                54864
JAMMU AND KASHMIR                      47553
ASSAM                                  44273
CHHATTISGARH                           44241
JHARKHAND                              34404
PUNJAB                                 26573
UTTARAKHAND                            21989
HIMACHAL PRADESH                       19064
MANIPUR                                 8946
PUDUCHERRY(UT)                          5810
TRIPURA                                 5098
GOA                                     4930
ARUNACHAL PRADESH                       4774
OUTSIDE-INDIA                           4750
MEGHALAYA                               3757
NAGALAND                                3705
CHANDIGARH(UT)                          3530
MIZORAM                                 2569
SIKKIM                                  1444
DADRA AND NAGAR HAVELI (UT)             1207
ANDAMAN AND NICOBAR ISLANDS (UT)        1025
DAMAN AND DIU (UT)                       769
LADAKH(UT)                               715
LAKSHADWEEP (UT)                         167

In [ ]:
df['between_400_700']=0

for i in range(len(df)):
    if df['Marks'][i] and  df['Marks'][i] <= 700:
        df['between_400_700'][i] = 1

        new = df.groupby('state').agg({'between_400_700':'sum','center_num':'count'})
        new['pct_of_students'] = new['between_400_700'] /new['center_num']*100
        print(100)

C:\Users\Hp\AppData\Local\Temp\ipykernel_20680\1638706843.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df['between_400_700'][i] = 1

KeyboardInterrupt:

In [ ]:
#Tareeka = 2 
df['between_400_700'] = (df['Marks']>= 400) & (df['Marks']<=700)

In [ ]:
#Tareeka = 3 
d = df.loc[(df['Marks']>= 400)  & (df['Marks']<=700),]

numerator_df = d.groupby('state').agg({'center_num':'count'}).sort_values(by='center_num',ascending= False).reset_index()
denominator_df = df.groupby('state').agg({'center_num':'count'}).sort_values(by='center_num',ascending= False)

In [ ]:
df.columns

In [ ]:
df.head()

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222

In [ ]:
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str

In [ ]:
e = df.loc[df[""]]

In [ ]:
d= df.loc[df['Marks']==720,]
print(c.groupby('city').agg({'Marks':'count'}))

                            Marks
city
AGARTALA                        1
AHMEDABAD                       2
AKOLA                           1
ANGAMALY                        1
BENGALURU- URBAN                2
BHATINDA                        1
CHENNAI                         4
DARBHANGA                       1
DELHI/NEW DELHI                 1
HALDWANI                        1
JAIPUR                          5
JHUNJHUNU                       1
KOLKATA                         1
KOLLAM                          1
KOTA                            2
KOTTAYAM                        1
KOZHIKODE/CALICUT               1
LUCKNOW                         2
MADHUBANI                       1
MANGALURU (MANGALORE)           1
MUMBAI                          2
MURSHIDABAD                     1
NAGPUR                          2
NAMAKKAL                        3
NANDED                          1
NAVI MUMBAI                     1
NELLORE                         1
NOIDA/GREATER NOIDA             1
PATIALA/FATEHGARH SAHIB         1
PATNA                           1
RAJKOT                          1
RANCHI                          1
SAHIBZADA AJIT SINGH NAGAR      2
SAMASTIPUR                      1
SIKAR                           3
SILIGURI                        1
SRIGANGANAGAR                   1
SURAT                           1
UDAIPUR                         1
VIJAYAWADA                      3
VILUPPURAM                      1

In [ ]:
df.groupby(['center_num']).agg({'Marks':['max','min']})

           Marks
             max min
center_num
110101       680  -5
110102       670  10
110103       648  11
120101       700  -3
120102       676  -5
...          ...  ..
991001       677  29
991101       662  20
991201       656  11
991301       697  -5
991401       608  29

[4750 rows x 2 columns]

In [ ]:
df.groupby(['state']).agg({'Marks':['max','min'],'center_num':['nunique'],'city':['nunique']})

                                 Marks      center_num    city
                                   max  min    nunique nunique
state
ANDAMAN AND NICOBAR ISLANDS (UT)   680   -5          3       1
ANDHRA PRADESH                     720  -89        126      27
ARUNACHAL PRADESH                  705  -16         11       3
ASSAM                              715 -102         99      17
BIHAR                              720 -180        227      35
CHANDIGARH(UT)                     715    0          4       1
CHHATTISGARH                       711  -44         96      19
DADRA AND NAGAR HAVELI (UT)        692  -10          4       1
DAMAN AND DIU (UT)                 665   -4          2       2
DELHI                              720  -36        116       1
GOA                                697  -35         16       2
GUJARAT                            720 -149        184      31
HARYANA                            716  -96        128      19
HIMACHAL PRADESH                   711  -49         52      10
JAMMU AND KASHMIR                  715  -56        107      10
JHARKHAND                          720  -50         74      22
KARNATAKA                          720  -87        328      32
KERALA                             720 -136        302      16
LADAKH(UT)                         533  -15          2       2
LAKSHADWEEP (UT)                   609   -8          1       1
MADHYA PRADESH                     715  -53        282      30
MAHARASHTRA                        720 -170        600      35
MANIPUR                            672  -48         25       3
MEGHALAYA                          692  -15         11       5
MIZORAM                            559  -12          7       1
NAGALAND                           648  -19         10       2
ODISHA                             715  -65        150      27
OUTSIDE-INDIA                      710   -5         14      14
PUDUCHERRY(UT)                     690  -24         11       4
PUNJAB                             720 -144         50      16
RAJASTHAN                          720 -135        392      25
SIKKIM                             656 -103          4       2
TAMIL NADU                         720  -38        271      31
TELANGANA                          715 -126        164      24
TRIPURA                            720  -35          9       2
UTTAR PRADESH                      720  -67        599      61
UTTARAKHAND                        720  -55         45      13
WEST BENGAL                        720 -135        224      20

In [ ]:
df.groupby(['state']).agg({'Marks':['max','min'],'center_num':['nunique']})

In [ ]:
df.groupby(['state','city']).agg({'Marks':['mean']})

                                                         Marks
                                                          mean
state                            city
ANDAMAN AND NICOBAR ISLANDS (UT) PORT BLAIR         192.737561
ANDHRA PRADESH                   ANANTAPUR          197.060985
                                 BHIMAVARAM         199.756728
                                 CHIRALA            202.297830
                                 CHITTOOR           174.487047
...                                                        ...
WEST BENGAL                      NORTH 24 PARGANAS  226.512949
                                 PURBA MEDINIPUR    191.416456
                                 SILIGURI           216.213010
                                 SOUTH 24 PARGANAS  192.899645
                                 SURI               191.236813

[567 rows x 1 columns]

In [ ]:
df.groupby('state').agg({'Marks':len})

                                   Marks
state
ANDAMAN AND NICOBAR ISLANDS (UT)    1025
ANDHRA PRADESH                     63846
ARUNACHAL PRADESH                   4774
ASSAM                              44273
BIHAR                             136193
CHANDIGARH(UT)                      3530
CHHATTISGARH                       44241
DADRA AND NAGAR HAVELI (UT)         1207
DAMAN AND DIU (UT)                   769
DELHI                              66090
GOA                                 4930
GUJARAT                            86952
HARYANA                            54864
HIMACHAL PRADESH                   19064
JAMMU AND KASHMIR                  47553
JHARKHAND                          34404
KARNATAKA                         150897
KERALA                            138546
LADAKH(UT)                           715
LAKSHADWEEP (UT)                     167
MADHYA PRADESH                    130238
MAHARASHTRA                       275245
MANIPUR                             8946
MEGHALAYA                           3757
MIZORAM                             2569
NAGALAND                            3705
ODISHA                             64318
OUTSIDE-INDIA                       4750
PUDUCHERRY(UT)                      5810
PUNJAB                             26573
RAJASTHAN                         193130
SIKKIM                              1444
TAMIL NADU                        153704
TELANGANA                          77892
TRIPURA                             5098
UTTAR PRADESH                     332631
UTTARAKHAND                        21989
WEST BENGAL                       117323

In [ ]:
df.groupby(['state','city']).agg({'center_num':'nunique'})

                                                    center_num
state                            city
ANDAMAN AND NICOBAR ISLANDS (UT) PORT BLAIR                  3
ANDHRA PRADESH                   ANANTAPUR                   4
                                 BHIMAVARAM                  1
                                 CHIRALA                     1
                                 CHITTOOR                    3
...                                                        ...
WEST BENGAL                      NORTH 24 PARGANAS          12
                                 PURBA MEDINIPUR             7
                                 SILIGURI                   10
                                 SOUTH 24 PARGANAS          13
                                 SURI                        5

[567 rows x 1 columns]

In [ ]:
df.groupby(['state','city']).agg({'center_num':'nunique'})

In [ ]:
df[["state","city"]]

                                    state        city
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

[2333162 rows x 2 columns]

In [ ]:
df[["city","state","center_num"]]

               city                             state  center_num
0        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
1        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
2        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
3        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
4        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
...             ...                               ...         ...
2333157     KALYANI                       WEST BENGAL      461312
2333158     KALYANI                       WEST BENGAL      461312
2333159     KALYANI                       WEST BENGAL      461312
2333160     KALYANI                       WEST BENGAL      461312
2333161     KALYANI                       WEST BENGAL      461312

[2333162 rows x 3 columns]

In [ ]:
df[['Marks', 'Srlno.', 'center_num', 'center_name', 'city', 'state']]

,Marks,Srlno.,center_num,center_name,city,state
0,46,1,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
1,226,2,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
2,449,3,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
3,424,4,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
4,222,5,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
...,...,...,...,...,...,...
2333157,279,135,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333158,102,136,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333159,14,137,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333160,179,138,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333161,91,139,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL

In [ ]:
df.head()

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222

In [ ]:
df.tail()

,state,city,center_name,center_num,Srlno.,Marks
2333157,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,135,279
2333158,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,136,102
2333159,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,137,14
2333160,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,138,179
2333161,WEST BENGAL,KALYANI,CHAKDAHA MODEL SCHOOL,461312,139,91

In [ ]:
df.iloc[0,5]

np.int64(46)

In [ ]:
df.iloc[0,[3,5]]

center_num    110101
Marks             46
Name: 0, dtype: int64

In [ ]:
df.iloc[[0,1],[1,2]]

         city               center_name
0  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
1  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1

In [ ]:
df.iloc[[2,5,8],[5]]

   Marks
2    449
5    181
8     88

In [ ]:
df.loc[[0,10,100,1000,10000],['state','city','Marks']]

                                  state        city  Marks
0      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR     46
10     ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    322
100    ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR      5
1000   ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR     73
10000                    ANDHRA PRADESH     NELLORE    458

In [ ]:
df.loc[df['state'] == 'CHHATTISGARH']

,state,city,center_name,center_num,Srlno.,Marks
253641,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,1,58
253642,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,2,374
253643,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,3,98
253644,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,4,221
253645,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,5,512
...,...,...,...,...,...,...
297877,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,521,120
297878,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,522,392
297879,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,523,120
297880,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,524,361
297881,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,525,321

In [ ]:
state = []

for i in df["state"]:
    if i not in state:
        state.append(i)
len(state)

38

In [ ]:
city  = []

for i in df["city"]:
    if i not in  city:
        city.append(i)
len(city)

567

In [ ]:
print(df.loc[df["city"] == "Mumbai"].shape) #ye bata raha hai ki kiya city mai mumbai bhi hai

(0, 6)

In [ ]:
print(df.loc[df["state"] == "Chhattisgarh"].shape)   # ye bata raha hai  ki state mai chhattisgrah hai

(0, 6)

In [ ]:
print(df["state"].unique()) # ye sab unique stae bata raha  hai

<StringArray>
['ANDAMAN AND NICOBAR ISLANDS (UT)',                   'ANDHRA PRADESH',
                'ARUNACHAL PRADESH',                            'ASSAM',
                            'BIHAR',                   'CHANDIGARH(UT)',
                     'CHHATTISGARH',      'DADRA AND NAGAR HAVELI (UT)',
               'DAMAN AND DIU (UT)',                            'DELHI',
                              'GOA',                          'GUJARAT',
                          'HARYANA',                 'HIMACHAL PRADESH',
                'JAMMU AND KASHMIR',                        'JHARKHAND',
                        'KARNATAKA',                           'KERALA',
                       'LADAKH(UT)',                 'LAKSHADWEEP (UT)',
                   'MADHYA PRADESH',                      'MAHARASHTRA',
                          'MANIPUR',                        'MEGHALAYA',
                          'MIZORAM',                         'NAGALAND',
                           'ODISHA',                    'OUTSIDE-INDIA',
                   'PUDUCHERRY(UT)',                           'PUNJAB',
                        'RAJASTHAN',                           'SIKKIM',
                       'TAMIL NADU',                        'TELANGANA',
                          'TRIPURA',                    'UTTAR PRADESH',
                      'UTTARAKHAND',                      'WEST BENGAL']
Length: 38, dtype: str

In [ ]:
print(df["state"].nunique())   # ye sare number of unique value bata raha hai

38

In [ ]:
print(df["city"].unique)    #ye sab unique city bat arahahi hamre dataset ka

<bound method Series.unique of 0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str>

In [ ]:
print(df["city"].nunique) #  ye total numebr of unique value bata  rahah hai

<bound method IndexOpsMixin.nunique of 0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str>

In [ ]:
cities = df.loc[df["state"] == "Chhattisgarh", "city"].unique()

print(len(cities))

0

In [ ]:
print(df.loc[df["city"] == "Raipur", "center_name"].nunique())

0

In [ ]:
df.loc[df["state"] == "CHHATTISGARH", "center_num"].nunique()

96

In [ ]:
df.loc[df["state"] == "CHHATTISGARH", "city"].unique()

<StringArray>
['BHILAI NAGAR/DURG',     'BILASPUR (CG)',            'RAIPUR',
         'AMBIKAPUR',             'BALOD',           'BIJAPUR',
         'DANTEWADA',          'DHAMTARI',         'JAGDALPUR',
           'JANJGIR',            'KANKER',         'KONDAGAON',
             'KORBA',        'MAHASAMUND',        'NARAYANPUR',
           'RAIGARH',       'RAJNANDGAON',             'SUKMA',
      'MANENDRAGARH']
Length: 19, dtype: str

In [ ]:
df.loc[df["city"] == "RAIPUR", "center_num"].nunique()

17

In [ ]:
print(df.loc[df["state"] == "OUTSIDE-INDIA", "city"].unique())

<StringArray>
[ 'KUWAIT CITY',        'DUBAI',    'ABU DHABI',      'BANGKOK',
      'COLOMBO',         'DOHA',    'KATHMANDU', 'KUALA LUMPUR',
        'LAGOS',       'MANAMA',       'MUSCAT',       'RIYADH',
      'SHARJAH',    'SINGAPORE']
Length: 14, dtype: str

In [ ]:
print(df.loc[df["state"] == "INDIA", "city"].unique())

<StringArray>
[]
Length: 0, dtype: str

In [ ]:
print(df.loc[df["state"] != "OUTSIDE-INDIA"].shape)

(2328412, 6)

In [ ]:
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [ ]:
print(df.loc[df['Marks'] < 0, 'Marks'].count())

9477

In [ ]:
print(df['Marks'].max())

720

In [ ]:
df.loc[df['Marks'] == max(df['Marks'])].shape

(61, 6)

In [ ]:
print(df.loc[df['Marks'] == max(df['Marks'])].shape)

(61, 6)

In [ ]:
df.loc[(df['Marks'] >= 715) & (df['Marks'] <= 720)].shape

(288, 6)

In [ ]:
counter = 0

for i in df['Marks']:
    if i >= 715 and i <= 720:
        counter = counter + 1

print(counter)

288

In [ ]:
(df.loc[(df['Marks'] > 700) & (df['Marks'] < 720)].shape[0] / df.shape[0]) * 100

0.06746209650251461

In [ ]:
#5. What percentage students scored between 700 to 720?
df.loc[(df['Marks'] < 100) | (df['Marks'] > 700)].shape[0]    # ye or ka symbol hai

695092

In [ ]:
#7. How many students from Chhattisgarh scored between 700 and 720?
df.loc[(df['state'] == 'Chhattisgarh') & (df['Marks'] >= 700) & (df['Marks'] <= 720)].shape[0]

0

In [ ]:
#8.How many students out of India scored between 700 and 720?
df.loc[(df['state'] != 'Chhattisgarh') & (df['Marks'] >= 700) & (df['Marks'] <= 720)].shape[0]

2321