In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("all_neet_marks_2607.csv")

In [3]:
# 1. How many students are present in the dataset
df.shape[0]

2333162

In [36]:
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [5]:
# 2. How many states are present
df["state"].nunique()

38

In [6]:
df["city"].nunique()  # tota number of uniwue value batata hai

567

In [34]:
df[["state","city"]]

                                    state        city
0        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
1        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
2        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
3        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
4        ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR
...                                   ...         ...
2333157                       WEST BENGAL     KALYANI
2333158                       WEST BENGAL     KALYANI
2333159                       WEST BENGAL     KALYANI
2333160                       WEST BENGAL     KALYANI
2333161                       WEST BENGAL     KALYANI

[2333162 rows x 2 columns]

In [35]:
df[["city","state","center_num"]]

               city                             state  center_num
0        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
1        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
2        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
3        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
4        PORT BLAIR  ANDAMAN AND NICOBAR ISLANDS (UT)      110101
...             ...                               ...         ...
2333157     KALYANI                       WEST BENGAL      461312
2333158     KALYANI                       WEST BENGAL      461312
2333159     KALYANI                       WEST BENGAL      461312
2333160     KALYANI                       WEST BENGAL      461312
2333161     KALYANI                       WEST BENGAL      461312

[2333162 rows x 3 columns]

In [38]:
df[['Marks', 'Srlno.', 'center_num', 'center_name', 'city', 'state']]

,Marks,Srlno.,center_num,center_name,city,state
0,46,1,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
1,226,2,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
2,449,3,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
3,424,4,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
4,222,5,110101,KENDRIYA VIDYALAYA NO. 1,PORT BLAIR,ANDAMAN AND NICOBAR ISLANDS (UT)
...,...,...,...,...,...,...
2333157,279,135,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333158,102,136,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333159,14,137,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333160,179,138,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL
2333161,91,139,461312,CHAKDAHA MODEL SCHOOL,KALYANI,WEST BENGAL

In [40]:
df.head()

,state,city,center_name,center_num,Srlno.,Marks
0,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,1,46
1,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,2,226
2,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,3,449
3,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,4,424
4,ANDAMAN AND NICOBAR ISLANDS (UT),PORT BLAIR,KENDRIYA VIDYALAYA NO. 1,110101,5,222

In [ ]:
df.tail()

In [42]:
df.iloc[0,5]

np.int64(46)

In [43]:
df.iloc[0,[3,5]]

center_num    110101
Marks             46
Name: 0, dtype: int64

In [44]:
df.iloc[[0,1],[1,2]]

         city               center_name
0  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1
1  PORT BLAIR  KENDRIYA VIDYALAYA NO. 1

In [45]:
df.iloc[[2,5,8],[5]]

   Marks
2    449
5    181
8     88

In [47]:
df.loc[[0,10,100,1000,10000],['state','city','Marks']]

                                  state        city  Marks
0      ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR     46
10     ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR    322
100    ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR      5
1000   ANDAMAN AND NICOBAR ISLANDS (UT)  PORT BLAIR     73
10000                    ANDHRA PRADESH     NELLORE    458

In [48]:
df.loc[df['state'] == 'CHHATTISGARH']

,state,city,center_name,center_num,Srlno.,Marks
253641,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,1,58
253642,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,2,374
253643,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,3,98
253644,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,4,221
253645,CHHATTISGARH,BHILAI NAGAR/DURG,SHRI SHANKARACHARYA VIDYALAYA,170101,5,512
...,...,...,...,...,...,...
297877,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,521,120
297878,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,522,392
297879,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,523,120
297880,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,524,361
297881,CHHATTISGARH,MANENDRAGARH,DELHI WORLD PUBLIC SCHOOL MDGR,171901,525,321

In [7]:
state = []

for i in df["state"]:
    if i not in state:
        state.append(i)
len(state)

38

In [8]:
city  = []

for i in df["city"]:
    if i not in  city:
        city.append(i)
len(city)

567

In [9]:
print(df.loc[df["city"] == "Mumbai"].shape) #ye bata raha hai ki kiya city mai mumbai bhi hai

(0, 6)

In [10]:
print(df.loc[df["state"] == "Chhattisgarh"].shape)   # ye bata raha hai  ki state mai chhattisgrah hai

(0, 6)

In [11]:
print(df["state"].unique()) # ye sab unique stae bata raha  hai

<StringArray>
['ANDAMAN AND NICOBAR ISLANDS (UT)',                   'ANDHRA PRADESH',
                'ARUNACHAL PRADESH',                            'ASSAM',
                            'BIHAR',                   'CHANDIGARH(UT)',
                     'CHHATTISGARH',      'DADRA AND NAGAR HAVELI (UT)',
               'DAMAN AND DIU (UT)',                            'DELHI',
                              'GOA',                          'GUJARAT',
                          'HARYANA',                 'HIMACHAL PRADESH',
                'JAMMU AND KASHMIR',                        'JHARKHAND',
                        'KARNATAKA',                           'KERALA',
                       'LADAKH(UT)',                 'LAKSHADWEEP (UT)',
                   'MADHYA PRADESH',                      'MAHARASHTRA',
                          'MANIPUR',                        'MEGHALAYA',
                          'MIZORAM',                         'NAGALAND',
                           'ODISHA',                    'OUTSIDE-INDIA',
                   'PUDUCHERRY(UT)',                           'PUNJAB',
                        'RAJASTHAN',                           'SIKKIM',
                       'TAMIL NADU',                        'TELANGANA',
                          'TRIPURA',                    'UTTAR PRADESH',
                      'UTTARAKHAND',                      'WEST BENGAL']
Length: 38, dtype: str

In [12]:
print(df["state"].nunique())   # ye sare number of unique value bata raha hai

38

In [13]:
print(df["city"].unique)    #ye sab unique city bat arahahi hamre dataset ka

<bound method Series.unique of 0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str>

In [14]:
print(df["city"].nunique) #  ye total numebr of unique value bata  rahah hai

<bound method IndexOpsMixin.nunique of 0          PORT BLAIR
1          PORT BLAIR
2          PORT BLAIR
3          PORT BLAIR
4          PORT BLAIR
              ...
2333157       KALYANI
2333158       KALYANI
2333159       KALYANI
2333160       KALYANI
2333161       KALYANI
Name: city, Length: 2333162, dtype: str>

In [15]:
cities = df.loc[df["state"] == "Chhattisgarh", "city"].unique()

print(len(cities))

0

In [16]:
print(df.loc[df["city"] == "Raipur", "center_name"].nunique())

0

In [17]:
df.loc[df["state"] == "CHHATTISGARH", "center_num"].nunique()

96

In [18]:
df.loc[df["state"] == "CHHATTISGARH", "city"].unique()

<StringArray>
['BHILAI NAGAR/DURG',     'BILASPUR (CG)',            'RAIPUR',
         'AMBIKAPUR',             'BALOD',           'BIJAPUR',
         'DANTEWADA',          'DHAMTARI',         'JAGDALPUR',
           'JANJGIR',            'KANKER',         'KONDAGAON',
             'KORBA',        'MAHASAMUND',        'NARAYANPUR',
           'RAIGARH',       'RAJNANDGAON',             'SUKMA',
      'MANENDRAGARH']
Length: 19, dtype: str

In [19]:
df.loc[df["city"] == "RAIPUR", "center_num"].nunique()

17

In [20]:
print(df.loc[df["state"] == "OUTSIDE-INDIA", "city"].unique())

<StringArray>
[ 'KUWAIT CITY',        'DUBAI',    'ABU DHABI',      'BANGKOK',
      'COLOMBO',         'DOHA',    'KATHMANDU', 'KUALA LUMPUR',
        'LAGOS',       'MANAMA',       'MUSCAT',       'RIYADH',
      'SHARJAH',    'SINGAPORE']
Length: 14, dtype: str

In [21]:
print(df.loc[df["state"] == "INDIA", "city"].unique())

<StringArray>
[]
Length: 0, dtype: str

In [22]:
print(df.loc[df["state"] != "OUTSIDE-INDIA"].shape)

(2328412, 6)

In [23]:
df.columns

Index(['state', 'city', 'center_name', 'center_num', 'Srlno.', 'Marks'], dtype='str')

In [24]:
print(df.loc[df['Marks'] < 0, 'Marks'].count())

9477

In [25]:
print(df['Marks'].max())

720

In [26]:
df.loc[df['Marks'] == max(df['Marks'])].shape

(61, 6)

In [27]:
print(df.loc[df['Marks'] == max(df['Marks'])].shape)

(61, 6)

In [28]:
df.loc[(df['Marks'] >= 715) & (df['Marks'] <= 720)].shape

(288, 6)

In [29]:
counter = 0

for i in df['Marks']:
    if i >= 715 and i <= 720:
        counter = counter + 1

print(counter)

288

In [30]:
(df.loc[(df['Marks'] > 700) & (df['Marks'] < 720)].shape[0] / df.shape[0]) * 100

0.06746209650251461

In [31]:
#5. What percentage students scored between 700 to 720?
df.loc[(df['Marks'] < 100) | (df['Marks'] > 700)].shape[0]    # ye or ka symbol hai

695092

In [32]:
#7. How many students from Chhattisgarh scored between 700 and 720?
df.loc[(df['state'] == 'Chhattisgarh') & (df['Marks'] >= 700) & (df['Marks'] <= 720)].shape[0]

0

In [33]:
#8.How many students out of India scored between 700 and 720?
df.loc[(df['state'] != 'Chhattisgarh') & (df['Marks'] >= 700) & (df['Marks'] <= 720)].shape[0]

2321